// <auto-generated>
// Shared backbone components for HEDIS Core resources.
// Generated at: 2026-02-24T19:44:50.1084595Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>Care team member who provided services.</summary>
public sealed record CareTeamComponent
{
    [JsonPropertyName("sequence")] public int? Sequence { get; init; }
    [JsonPropertyName("provider")] public ResourceReference? Provider { get; init; }
    [JsonPropertyName("responsible")] public bool? Responsible { get; init; }
    [JsonPropertyName("role")] public CodeableConcept? Role { get; init; }
    [JsonPropertyName("qualification")] public CodeableConcept? Qualification { get; init; }
}

/// <summary>Diagnosis information.</summary>
public sealed record DiagnosisComponent
{
    [JsonPropertyName("sequence")] public int? Sequence { get; init; }
    [JsonPropertyName("diagnosisCodeableConcept")] public CodeableConcept? DiagnosisCodeableConcept { get; init; }
    [JsonPropertyName("diagnosisReference")] public ResourceReference? DiagnosisReference { get; init; }
    [JsonPropertyName("type")] public List<CodeableConcept>? Type { get; init; }
    [JsonPropertyName("onAdmission")] public CodeableConcept? OnAdmission { get; init; }
    [JsonPropertyName("packageCode")] public CodeableConcept? PackageCode { get; init; }
}

/// <summary>Procedure information.</summary>
public sealed record ProcedureComponent
{
    [JsonPropertyName("sequence")] public int? Sequence { get; init; }
    [JsonPropertyName("type")] public List<CodeableConcept>? Type { get; init; }
    [JsonPropertyName("date")] public string? Date { get; init; }
    [JsonPropertyName("procedureCodeableConcept")] public CodeableConcept? ProcedureCodeableConcept { get; init; }
    [JsonPropertyName("procedureReference")] public ResourceReference? ProcedureReference { get; init; }
    [JsonPropertyName("udi")] public List<ResourceReference>? Udi { get; init; }
}

/// <summary>Supporting information.</summary>
public sealed record SupportingInfoComponent
{
    [JsonPropertyName("sequence")] public int? Sequence { get; init; }
    [JsonPropertyName("category")] public CodeableConcept? Category { get; init; }
    [JsonPropertyName("code")] public CodeableConcept? Code { get; init; }
    [JsonPropertyName("timingDate")] public string? TimingDate { get; init; }
    [JsonPropertyName("timingPeriod")] public Period? TimingPeriod { get; init; }
    [JsonPropertyName("valueBoolean")] public bool? ValueBoolean { get; init; }
    [JsonPropertyName("valueString")] public string? ValueString { get; init; }
    [JsonPropertyName("valueQuantity")] public Quantity? ValueQuantity { get; init; }
    [JsonPropertyName("valueAttachment")] public Attachment? ValueAttachment { get; init; }
    [JsonPropertyName("valueReference")] public ResourceReference? ValueReference { get; init; }
    [JsonPropertyName("reason")] public CodeableConcept? Reason { get; init; }
}

/// <summary>Line item for claim or explanation of benefit.</summary>
public sealed record ItemComponent
{
    [JsonPropertyName("sequence")] public int? Sequence { get; init; }
    [JsonPropertyName("careTeamSequence")] public List<int>? CareTeamSequence { get; init; }
    [JsonPropertyName("diagnosisSequence")] public List<int>? DiagnosisSequence { get; init; }
    [JsonPropertyName("procedureSequence")] public List<int>? ProcedureSequence { get; init; }
    [JsonPropertyName("informationSequence")] public List<int>? InformationSequence { get; init; }
    [JsonPropertyName("revenue")] public CodeableConcept? Revenue { get; init; }
    [JsonPropertyName("category")] public CodeableConcept? Category { get; init; }
    [JsonPropertyName("productOrService")] public CodeableConcept? ProductOrService { get; init; }
    [JsonPropertyName("modifier")] public List<CodeableConcept>? Modifier { get; init; }
    [JsonPropertyName("programCode")] public List<CodeableConcept>? ProgramCode { get; init; }
    [JsonPropertyName("servicedDate")] public string? ServicedDate { get; init; }
    [JsonPropertyName("servicedPeriod")] public Period? ServicedPeriod { get; init; }
    [JsonPropertyName("locationCodeableConcept")] public CodeableConcept? LocationCodeableConcept { get; init; }
    [JsonPropertyName("locationAddress")] public Address? LocationAddress { get; init; }
    [JsonPropertyName("locationReference")] public ResourceReference? LocationReference { get; init; }
    [JsonPropertyName("quantity")] public Quantity? Quantity { get; init; }
    [JsonPropertyName("unitPrice")] public Money? UnitPrice { get; init; }
    [JsonPropertyName("factor")] public decimal? Factor { get; init; }
    [JsonPropertyName("net")] public Money? Net { get; init; }
    [JsonPropertyName("udi")] public List<ResourceReference>? Udi { get; init; }
    [JsonPropertyName("bodySite")] public CodeableConcept? BodySite { get; init; }
    [JsonPropertyName("subSite")] public List<CodeableConcept>? SubSite { get; init; }
    [JsonPropertyName("encounter")] public List<ResourceReference>? Encounter { get; init; }
    [JsonPropertyName("noteNumber")] public List<int>? NoteNumber { get; init; }
    [JsonPropertyName("adjudication")] public List<AdjudicationComponent>? Adjudication { get; init; }
    [JsonPropertyName("detail")] public List<ItemDetailComponent>? Detail { get; init; }
}

/// <summary>Adjudication details.</summary>
public sealed record AdjudicationComponent
{
    [JsonPropertyName("category")] public CodeableConcept? Category { get; init; }
    [JsonPropertyName("reason")] public CodeableConcept? Reason { get; init; }
    [JsonPropertyName("amount")] public Money? Amount { get; init; }
    [JsonPropertyName("value")] public decimal? Value { get; init; }
}

/// <summary>Item detail component.</summary>
public sealed record ItemDetailComponent
{
    [JsonPropertyName("sequence")] public int? Sequence { get; init; }
    [JsonPropertyName("revenue")] public CodeableConcept? Revenue { get; init; }
    [JsonPropertyName("category")] public CodeableConcept? Category { get; init; }
    [JsonPropertyName("productOrService")] public CodeableConcept? ProductOrService { get; init; }
    [JsonPropertyName("modifier")] public List<CodeableConcept>? Modifier { get; init; }
    [JsonPropertyName("programCode")] public List<CodeableConcept>? ProgramCode { get; init; }
    [JsonPropertyName("quantity")] public Quantity? Quantity { get; init; }
    [JsonPropertyName("unitPrice")] public Money? UnitPrice { get; init; }
    [JsonPropertyName("factor")] public decimal? Factor { get; init; }
    [JsonPropertyName("net")] public Money? Net { get; init; }
    [JsonPropertyName("udi")] public List<ResourceReference>? Udi { get; init; }
    [JsonPropertyName("noteNumber")] public List<int>? NoteNumber { get; init; }
    [JsonPropertyName("adjudication")] public List<AdjudicationComponent>? Adjudication { get; init; }
    [JsonPropertyName("subDetail")] public List<ItemSubDetailComponent>? SubDetail { get; init; }
}

/// <summary>Item sub-detail component.</summary>
public sealed record ItemSubDetailComponent
{
    [JsonPropertyName("sequence")] public int? Sequence { get; init; }
    [JsonPropertyName("revenue")] public CodeableConcept? Revenue { get; init; }
    [JsonPropertyName("category")] public CodeableConcept? Category { get; init; }
    [JsonPropertyName("productOrService")] public CodeableConcept? ProductOrService { get; init; }
    [JsonPropertyName("modifier")] public List<CodeableConcept>? Modifier { get; init; }
    [JsonPropertyName("programCode")] public List<CodeableConcept>? ProgramCode { get; init; }
    [JsonPropertyName("quantity")] public Quantity? Quantity { get; init; }
    [JsonPropertyName("unitPrice")] public Money? UnitPrice { get; init; }
    [JsonPropertyName("factor")] public decimal? Factor { get; init; }
    [JsonPropertyName("net")] public Money? Net { get; init; }
    [JsonPropertyName("udi")] public List<ResourceReference>? Udi { get; init; }
    [JsonPropertyName("noteNumber")] public List<int>? NoteNumber { get; init; }
    [JsonPropertyName("adjudication")] public List<AdjudicationComponent>? Adjudication { get; init; }
}

/// <summary>Total amount for the category.</summary>
public sealed record TotalComponent
{
    [JsonPropertyName("category")] public CodeableConcept? Category { get; init; }
    [JsonPropertyName("amount")] public Money? Amount { get; init; }
}

/// <summary>Payment details.</summary>
public sealed record PaymentComponent
{
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }
    [JsonPropertyName("adjustment")] public Money? Adjustment { get; init; }
    [JsonPropertyName("adjustmentReason")] public CodeableConcept? AdjustmentReason { get; init; }
    [JsonPropertyName("date")] public string? Date { get; init; }
    [JsonPropertyName("amount")] public Money? Amount { get; init; }
    [JsonPropertyName("identifier")] public Identifier? Identifier { get; init; }
}

/// <summary>Insurance information.</summary>
public sealed record InsuranceComponent
{
    [JsonPropertyName("focal")] public bool? Focal { get; init; }
    [JsonPropertyName("coverage")] public ResourceReference? Coverage { get; init; }
    [JsonPropertyName("preAuthRef")] public List<string>? PreAuthRef { get; init; }
}

/// <summary>Accident information.</summary>
public sealed record AccidentComponent
{
    [JsonPropertyName("date")] public string? Date { get; init; }
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }
    [JsonPropertyName("locationAddress")] public Address? LocationAddress { get; init; }
    [JsonPropertyName("locationReference")] public ResourceReference? LocationReference { get; init; }
}

/// <summary>Related claim information.</summary>
public sealed record RelatedClaimComponent
{
    [JsonPropertyName("claim")] public ResourceReference? Claim { get; init; }
    [JsonPropertyName("relationship")] public CodeableConcept? Relationship { get; init; }
    [JsonPropertyName("reference")] public Identifier? Reference { get; init; }
}

/// <summary>Payee information.</summary>
public sealed record PayeeComponent
{
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }
    [JsonPropertyName("party")] public ResourceReference? Party { get; init; }
}

/// <summary>Benefit balance information.</summary>
public sealed record BenefitBalanceComponent
{
    [JsonPropertyName("category")] public CodeableConcept? Category { get; init; }
    [JsonPropertyName("excluded")] public bool? Excluded { get; init; }
    [JsonPropertyName("name")] public string? Name { get; init; }
    [JsonPropertyName("description")] public string? Description { get; init; }
    [JsonPropertyName("network")] public CodeableConcept? Network { get; init; }
    [JsonPropertyName("unit")] public CodeableConcept? Unit { get; init; }
    [JsonPropertyName("term")] public CodeableConcept? Term { get; init; }
    [JsonPropertyName("financial")] public List<BenefitComponent>? Financial { get; init; }
}

/// <summary>Benefit information.</summary>
public sealed record BenefitComponent
{
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }
    [JsonPropertyName("allowedUnsignedInt")] public uint? AllowedUnsignedInt { get; init; }
    [JsonPropertyName("allowedString")] public string? AllowedString { get; init; }
    [JsonPropertyName("allowedMoney")] public Money? AllowedMoney { get; init; }
    [JsonPropertyName("usedUnsignedInt")] public uint? UsedUnsignedInt { get; init; }
    [JsonPropertyName("usedMoney")] public Money? UsedMoney { get; init; }
}

/// <summary>Note information.</summary>
public sealed record NoteComponent
{
    [JsonPropertyName("number")] public int? Number { get; init; }
    [JsonPropertyName("type")] public string? Type { get; init; }
    [JsonPropertyName("text")] public string? Text { get; init; }
    [JsonPropertyName("language")] public CodeableConcept? Language { get; init; }
}

/// <summary>Component results for an observation.</summary>
public sealed record ObservationComponent
{
    [JsonPropertyName("code")] public CodeableConcept? Code { get; init; }
    [JsonPropertyName("valueQuantity")] public Quantity? ValueQuantity { get; init; }
    [JsonPropertyName("valueCodeableConcept")] public CodeableConcept? ValueCodeableConcept { get; init; }
    [JsonPropertyName("valueString")] public string? ValueString { get; init; }
    [JsonPropertyName("valueBoolean")] public bool? ValueBoolean { get; init; }
    [JsonPropertyName("valueInteger")] public int? ValueInteger { get; init; }
    [JsonPropertyName("valueRange")] public Range? ValueRange { get; init; }
    [JsonPropertyName("valueRatio")] public Ratio? ValueRatio { get; init; }
    [JsonPropertyName("valueSampledData")] public SampledData? ValueSampledData { get; init; }
    [JsonPropertyName("valueTime")] public string? ValueTime { get; init; }
    [JsonPropertyName("valueDateTime")] public string? ValueDateTime { get; init; }
    [JsonPropertyName("valuePeriod")] public Period? ValuePeriod { get; init; }
    [JsonPropertyName("dataAbsentReason")] public CodeableConcept? DataAbsentReason { get; init; }
    [JsonPropertyName("interpretation")] public List<CodeableConcept>? Interpretation { get; init; }
    [JsonPropertyName("referenceRange")] public List<ReferenceRangeComponent>? ReferenceRange { get; init; }
}

/// <summary>Reference range for an observation.</summary>
public sealed record ReferenceRangeComponent
{
    [JsonPropertyName("low")] public Quantity? Low { get; init; }
    [JsonPropertyName("high")] public Quantity? High { get; init; }
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }
    [JsonPropertyName("appliesTo")] public List<CodeableConcept>? AppliesTo { get; init; }
    [JsonPropertyName("age")] public Range? Age { get; init; }
    [JsonPropertyName("text")] public string? Text { get; init; }
}

/// <summary>Performer information.</summary>
public sealed record PerformerComponent
{
    [JsonPropertyName("function")] public CodeableConcept? Function { get; init; }
    [JsonPropertyName("actor")] public ResourceReference? Actor { get; init; }
}

/// <summary>Participant in an encounter.</summary>
public sealed record ParticipantComponent
{
    [JsonPropertyName("type")] public List<CodeableConcept>? Type { get; init; }
    [JsonPropertyName("period")] public Period? Period { get; init; }
    [JsonPropertyName("individual")] public ResourceReference? Individual { get; init; }
}

/// <summary>Location during an encounter.</summary>
public sealed record LocationComponent
{
    [JsonPropertyName("location")] public ResourceReference? Location { get; init; }
    [JsonPropertyName("status")] public string? Status { get; init; }
    [JsonPropertyName("physicalType")] public CodeableConcept? PhysicalType { get; init; }
    [JsonPropertyName("period")] public Period? Period { get; init; }
}

/// <summary>Hospitalization details.</summary>
public sealed record HospitalizationComponent
{
    [JsonPropertyName("preAdmissionIdentifier")] public Identifier? PreAdmissionIdentifier { get; init; }
    [JsonPropertyName("origin")] public ResourceReference? Origin { get; init; }
    [JsonPropertyName("admitSource")] public CodeableConcept? AdmitSource { get; init; }
    [JsonPropertyName("reAdmission")] public CodeableConcept? ReAdmission { get; init; }
    [JsonPropertyName("dietPreference")] public List<CodeableConcept>? DietPreference { get; init; }
    [JsonPropertyName("specialCourtesy")] public List<CodeableConcept>? SpecialCourtesy { get; init; }
    [JsonPropertyName("specialArrangement")] public List<CodeableConcept>? SpecialArrangement { get; init; }
    [JsonPropertyName("destination")] public ResourceReference? Destination { get; init; }
    [JsonPropertyName("dischargeDisposition")] public CodeableConcept? DischargeDisposition { get; init; }
}

/// <summary>Class history for an encounter.</summary>
public sealed record ClassHistoryComponent
{
    [JsonPropertyName("class")] public Coding? Class { get; init; }
    [JsonPropertyName("period")] public Period? Period { get; init; }
}

/// <summary>Status history for an encounter.</summary>
public sealed record StatusHistoryComponent
{
    [JsonPropertyName("status")] public string? Status { get; init; }
    [JsonPropertyName("period")] public Period? Period { get; init; }
}

/// <summary>Diagnosis information for an encounter.</summary>
public sealed record EncounterDiagnosisComponent
{
    [JsonPropertyName("condition")] public ResourceReference? Condition { get; init; }
    [JsonPropertyName("use")] public CodeableConcept? Use { get; init; }
    [JsonPropertyName("rank")] public int? Rank { get; init; }
}

/// <summary>Stage information for a condition.</summary>
public sealed record StageComponent
{
    [JsonPropertyName("summary")] public CodeableConcept? Summary { get; init; }
    [JsonPropertyName("assessment")] public List<ResourceReference>? Assessment { get; init; }
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }
}

/// <summary>Evidence for a condition.</summary>
public sealed record EvidenceComponent
{
    [JsonPropertyName("code")] public List<CodeableConcept>? Code { get; init; }
    [JsonPropertyName("detail")] public List<ResourceReference>? Detail { get; init; }
}

/// <summary>Coverage class information.</summary>
public sealed record CoverageClassComponent
{
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }
    [JsonPropertyName("value")] public string? Value { get; init; }
    [JsonPropertyName("name")] public string? Name { get; init; }
}

/// <summary>Cost to beneficiary information.</summary>
public sealed record CostToBeneficiaryComponent
{
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }
    [JsonPropertyName("valueQuantity")] public Quantity? ValueQuantity { get; init; }
    [JsonPropertyName("valueMoney")] public Money? ValueMoney { get; init; }
    [JsonPropertyName("exception")] public List<ExceptionComponent>? Exception { get; init; }
}

/// <summary>Exception information.</summary>
public sealed record ExceptionComponent
{
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }
    [JsonPropertyName("period")] public Period? Period { get; init; }
}

/// <summary>Contact party for a patient.</summary>
public sealed record ContactComponent
{
    [JsonPropertyName("relationship")] public List<CodeableConcept>? Relationship { get; init; }
    [JsonPropertyName("name")] public HumanName? Name { get; init; }
    [JsonPropertyName("telecom")] public List<ContactPoint>? Telecom { get; init; }
    [JsonPropertyName("address")] public Address? Address { get; init; }
    [JsonPropertyName("gender")] public string? Gender { get; init; }
    [JsonPropertyName("organization")] public ResourceReference? Organization { get; init; }
    [JsonPropertyName("period")] public Period? Period { get; init; }
}

/// <summary>Communication preferences.</summary>
public sealed record CommunicationComponent
{
    [JsonPropertyName("language")] public CodeableConcept? Language { get; init; }
    [JsonPropertyName("preferred")] public bool? Preferred { get; init; }
}

/// <summary>Link to another patient resource.</summary>
public sealed record LinkComponent
{
    [JsonPropertyName("other")] public ResourceReference? Other { get; init; }
    [JsonPropertyName("type")] public string? Type { get; init; }
}

/// <summary>Reaction information for an immunization.</summary>
public sealed record ReactionComponent
{
    [JsonPropertyName("date")] public string? Date { get; init; }
    [JsonPropertyName("detail")] public ResourceReference? Detail { get; init; }
    [JsonPropertyName("reported")] public bool? Reported { get; init; }
}

/// <summary>Protocol applied for an immunization.</summary>
public sealed record ProtocolAppliedComponent
{
    [JsonPropertyName("series")] public string? Series { get; init; }
    [JsonPropertyName("authority")] public ResourceReference? Authority { get; init; }
    [JsonPropertyName("targetDisease")] public List<CodeableConcept>? TargetDisease { get; init; }
    [JsonPropertyName("doseNumberPositiveInt")] public uint? DoseNumberPositiveInt { get; init; }
    [JsonPropertyName("doseNumberString")] public string? DoseNumberString { get; init; }
    [JsonPropertyName("seriesDosesPositiveInt")] public uint? SeriesDosesPositiveInt { get; init; }
    [JsonPropertyName("seriesDosesString")] public string? SeriesDosesString { get; init; }
}

/// <summary>Educational material presented to patient.</summary>
public sealed record EducationComponent
{
    [JsonPropertyName("documentType")] public string? DocumentType { get; init; }
    [JsonPropertyName("reference")] public string? Reference { get; init; }
    [JsonPropertyName("publicationDate")] public string? PublicationDate { get; init; }
    [JsonPropertyName("presentationDate")] public string? PresentationDate { get; init; }
}

/// <summary>Item in a questionnaire response.</summary>
public sealed record QuestionnaireItemComponent
{
    [JsonPropertyName("linkId")] public string? LinkId { get; init; }
    [JsonPropertyName("definition")] public string? Definition { get; init; }
    [JsonPropertyName("text")] public string? Text { get; init; }
    [JsonPropertyName("answer")] public List<QuestionnaireAnswerComponent>? Answer { get; init; }
    [JsonPropertyName("item")] public List<QuestionnaireItemComponent>? Item { get; init; }
}

/// <summary>Answer to a questionnaire item.</summary>
public sealed record QuestionnaireAnswerComponent
{
    [JsonPropertyName("valueBoolean")] public bool? ValueBoolean { get; init; }
    [JsonPropertyName("valueDecimal")] public decimal? ValueDecimal { get; init; }
    [JsonPropertyName("valueInteger")] public int? ValueInteger { get; init; }
    [JsonPropertyName("valueDate")] public string? ValueDate { get; init; }
    [JsonPropertyName("valueDateTime")] public string? ValueDateTime { get; init; }
    [JsonPropertyName("valueTime")] public string? ValueTime { get; init; }
    [JsonPropertyName("valueString")] public string? ValueString { get; init; }
    [JsonPropertyName("valueUri")] public string? ValueUri { get; init; }
    [JsonPropertyName("valueAttachment")] public Attachment? ValueAttachment { get; init; }
    [JsonPropertyName("valueCoding")] public Coding? ValueCoding { get; init; }
    [JsonPropertyName("valueQuantity")] public Quantity? ValueQuantity { get; init; }
    [JsonPropertyName("valueReference")] public ResourceReference? ValueReference { get; init; }
    [JsonPropertyName("item")] public List<QuestionnaireItemComponent>? Item { get; init; }
}

/// <summary>Focal device for a procedure.</summary>
public sealed record FocalDeviceComponent
{
    [JsonPropertyName("action")] public CodeableConcept? Action { get; init; }
    [JsonPropertyName("manipulated")] public ResourceReference? Manipulated { get; init; }
}

/// <summary>Geographic position of a location.</summary>
public sealed record PositionComponent
{
    [JsonPropertyName("longitude")] public decimal? Longitude { get; init; }
    [JsonPropertyName("latitude")] public decimal? Latitude { get; init; }
    [JsonPropertyName("altitude")] public decimal? Altitude { get; init; }
}

/// <summary>Hours of operation for a location.</summary>
public sealed record HoursOfOperationComponent
{
    [JsonPropertyName("daysOfWeek")] public List<string>? DaysOfWeek { get; init; }
    [JsonPropertyName("allDay")] public bool? AllDay { get; init; }
    [JsonPropertyName("openingTime")] public string? OpeningTime { get; init; }
    [JsonPropertyName("closingTime")] public string? ClosingTime { get; init; }
}

/// <summary>Qualification for a practitioner.</summary>
public sealed record QualificationComponent
{
    [JsonPropertyName("identifier")] public List<Identifier>? Identifier { get; init; }
    [JsonPropertyName("code")] public CodeableConcept? Code { get; init; }
    [JsonPropertyName("period")] public Period? Period { get; init; }
    [JsonPropertyName("issuer")] public ResourceReference? Issuer { get; init; }
}

/// <summary>Available time for a practitioner role.</summary>
public sealed record AvailableTimeComponent
{
    [JsonPropertyName("daysOfWeek")] public List<string>? DaysOfWeek { get; init; }
    [JsonPropertyName("allDay")] public bool? AllDay { get; init; }
    [JsonPropertyName("availableStartTime")] public string? AvailableStartTime { get; init; }
    [JsonPropertyName("availableEndTime")] public string? AvailableEndTime { get; init; }
}

/// <summary>Not available time for a practitioner role.</summary>
public sealed record NotAvailableComponent
{
    [JsonPropertyName("description")] public string? Description { get; init; }
    [JsonPropertyName("during")] public Period? During { get; init; }
}

/// <summary>Document content information.</summary>
public sealed record ContentComponent
{
    [JsonPropertyName("attachment")] public Attachment? Attachment { get; init; }
    [JsonPropertyName("format")] public Coding? Format { get; init; }
}

/// <summary>Clinical context for a document.</summary>
public sealed record ContextComponent
{
    [JsonPropertyName("encounter")] public List<ResourceReference>? Encounter { get; init; }
    [JsonPropertyName("event")] public List<CodeableConcept>? Event { get; init; }
    [JsonPropertyName("period")] public Period? Period { get; init; }
    [JsonPropertyName("facilityType")] public CodeableConcept? FacilityType { get; init; }
    [JsonPropertyName("practiceSetting")] public CodeableConcept? PracticeSetting { get; init; }
    [JsonPropertyName("sourcePatientInfo")] public ResourceReference? SourcePatientInfo { get; init; }
    [JsonPropertyName("related")] public List<ResourceReference>? Related { get; init; }
}

/// <summary>Document relationship information.</summary>
public sealed record RelatesToComponent
{
    [JsonPropertyName("code")] public string? Code { get; init; }
    [JsonPropertyName("target")] public ResourceReference? Target { get; init; }
}

/// <summary>Ingredient information for a medication.</summary>
public sealed record IngredientComponent
{
    [JsonPropertyName("itemCodeableConcept")] public CodeableConcept? ItemCodeableConcept { get; init; }
    [JsonPropertyName("itemReference")] public ResourceReference? ItemReference { get; init; }
    [JsonPropertyName("isActive")] public bool? IsActive { get; init; }
    [JsonPropertyName("strength")] public Ratio? Strength { get; init; }
}

/// <summary>Batch information for a medication.</summary>
public sealed record BatchComponent
{
    [JsonPropertyName("lotNumber")] public string? LotNumber { get; init; }
    [JsonPropertyName("expirationDate")] public string? ExpirationDate { get; init; }
}

