// <auto-generated>
// HEDIS Core Bundle - Union of 1 profile(s).
//   - http://hl7.org/fhir/StructureDefinition/Bundle
// Generated at: 2026-03-13T03:00:24.4215359Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Bundle.
/// </summary>
public sealed record Bundle
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Bundle";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Entry in the bundle - will have a resource or information</summary>
    [JsonPropertyName("entry")] public List<BundleEntryComponent>? Entry { get; init; }

    /// <summary>Persistent identifier for the bundle</summary>
    [JsonPropertyName("identifier")] public Identifier? Identifier { get; init; }

    /// <summary>Links related to this Bundle</summary>
    [JsonPropertyName("link")] public List<BundleLinkComponent>? Link { get; init; }

    /// <summary>Digital Signature</summary>
    [JsonPropertyName("signature")] public Signature? Signature { get; init; }

    /// <summary>When the bundle was assembled</summary>
    [JsonPropertyName("timestamp")] public string? Timestamp { get; init; }

    /// <summary>If search, the total number of matches</summary>
    [JsonPropertyName("total")] public uint? Total { get; init; }

    /// <summary>document | message | transaction | transaction-response | batch | batch-response | history | searchset | collection</summary>
    [JsonPropertyName("type")] public string? Type { get; init; }

}
