// <auto-generated>
// HEDIS Core Claim - Union of 4 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-claim-inpatient-institutional
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-claim-outpatient-institutional
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-claim-pharmacy
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-claim-professional-nonclinician
// Generated at: 2026-02-24T19:44:50.1119942Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Claim.
/// <para>Union of 4 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record Claim
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Claim";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")] public string? ImplicitRules { get; init; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")] public string? Language { get; init; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")] public Narrative? Text { get; init; }

    /// <summary>Contained, inline Resources.</summary>
    [JsonPropertyName("contained")] public List<object>? Contained { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")] public List<Extension>? ModifierExtension { get; init; }

    /// <summary>[CARIN-BB] The period for which charges are being submitted.</summary>
    [JsonPropertyName("billablePeriod")] public Period? BillablePeriod { get; init; }

    /// <summary>[CARIN-BB] The members of the team who provided the products and services.</summary>
    [JsonPropertyName("careTeam")] public List<CareTeamComponent>? CareTeam { get; init; }

    /// <summary>[CARIN-BB] Information about diagnoses relevant to the claim items.</summary>
    [JsonPropertyName("diagnosis")] public List<DiagnosisComponent>? Diagnosis { get; init; }

    /// <summary>[HEDIS][CARIN-BB] A claim line. Either a simple  product or service or a 'group' of details which can each be a simple items or groups of sub-details.</summary>
    [JsonPropertyName("item")] public List<ItemComponent>? Item { get; init; }

    /// <summary>[HEDIS] The party to whom the professional services and/or products have been supplied or are being considered and for whom actual or forecast reimbursement is sought.</summary>
    [JsonPropertyName("patient")] public ResourceReference? Patient { get; init; }

    /// <summary>[CARIN-BB] Procedures performed on the patient relevant to the billing items with the claim.</summary>
    [JsonPropertyName("procedure")] public List<ProcedureComponent>? Procedure { get; init; }

    /// <summary>[CARIN-BB] A finer grained suite of claim type codes which may convey additional information such as Inpatient vs Outpatient and/or a specialty service.</summary>
    [JsonPropertyName("subType")] public CodeableConcept? SubType { get; init; }

    /// <summary>[CARIN-BB] Additional information codes regarding exceptions, special considerations, the condition, situation, prior or concurrent issues.</summary>
    [JsonPropertyName("supportingInfo")] public List<SupportingInfoComponent>? SupportingInfo { get; init; }

    /// <summary>[CARIN-BB] The category of claim, e.g. oral, pharmacy, vision, institutional, professional.</summary>
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }

}
