// <auto-generated>
// HEDIS Core ClaimResponse - Union of 2 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-claimresponse
//   - http://hl7.org/fhir/StructureDefinition/ClaimResponse
// Generated at: 2026-03-13T03:00:24.4254238Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core ClaimResponse.
/// <para>Union of 2 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record ClaimResponse
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "ClaimResponse";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>[HEDIS] The first-tier service adjudications for payor added product or service lines.</summary>
    [JsonPropertyName("addItem")] public List<object>? AddItem { get; init; }

    /// <summary>[HEDIS] Original request resource reference.</summary>
    [JsonPropertyName("request")] public object? Request { get; init; }

    /// <summary>[HEDIS] A finer grained suite of claim type codes which may convey additional information such as Inpatient vs Outpatient and/or a specialty service.</summary>
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }

}
