// <auto-generated>
// HEDIS Core ClaimResponse - Union of 1 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-claimresponse
// Generated at: 2026-02-24T19:44:50.1166144Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core ClaimResponse.
/// </summary>
public sealed record ClaimResponse
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "ClaimResponse";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")] public string? ImplicitRules { get; init; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")] public string? Language { get; init; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")] public Narrative? Text { get; init; }

    /// <summary>Contained, inline Resources.</summary>
    [JsonPropertyName("contained")] public List<object>? Contained { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")] public List<Extension>? ModifierExtension { get; init; }

    /// <summary>[HEDIS] The first-tier service adjudications for payor added product or service lines.</summary>
    [JsonPropertyName("addItem")] public object? AddItem { get; init; }

    /// <summary>[HEDIS] The party to whom the professional services and/or products have been supplied or are being considered and for whom actual for facast reimbursement is sought.</summary>
    [JsonPropertyName("patient")] public ResourceReference? Patient { get; init; }

    /// <summary>[HEDIS] Original request resource reference.</summary>
    [JsonPropertyName("request")] public object? Request { get; init; }

    /// <summary>[HEDIS] A finer grained suite of claim type codes which may convey additional information such as Inpatient vs Outpatient and/or a specialty service.</summary>
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }

}
