// <auto-generated>
// HEDIS Core Condition - Union of 3 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-condition-encounter-diagnosis
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-condition-problems-health-concerns
//   - http://hl7.org/fhir/StructureDefinition/Condition
// Generated at: 2026-03-13T03:00:24.4257246Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Condition.
/// <para>Union of 3 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record Condition
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Condition";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>[HEDIS][US Core] The date or estimated date that the condition resolved or went into remission. This is called "abatement" because of the many overloaded connotations associated with "remission" or "resolution" - Conditions are never really resolved, but they can abate.</summary>
    [JsonPropertyName("abatement")] public string? Abatement { get; init; }

    [JsonPropertyName("category")] public List<CodeableConcept>? Category { get; init; }

    /// <summary>[US Core] The clinical status of the condition.</summary>
    [JsonPropertyName("clinicalStatus")] public object? ClinicalStatus { get; init; }

    /// <summary>[US Core] Identification of the condition, problem or diagnosis.</summary>
    [JsonPropertyName("code")] public CodeableConcept? Code { get; init; }

    /// <summary>[US Core] The Encounter during which this Condition was created or to which the creation of this record is tightly associated.</summary>
    [JsonPropertyName("encounter")] public ResourceReference? Encounter { get; init; }

    /// <summary>[HEDIS][US Core] Estimated or actual date or date-time  the condition began, in the opinion of the clinician.</summary>
    [JsonPropertyName("onset")] public string? Onset { get; init; }

    /// <summary>[US Core] The recordedDate represents when this particular Condition record was created in the system, which is often a system-generated date.</summary>
    [JsonPropertyName("recordedDate")] public object? RecordedDate { get; init; }

    /// <summary>[HEDIS] Indicates the patient or group who the condition record is associated with.</summary>
    [JsonPropertyName("subject")] public ResourceReference? Subject { get; init; }

    /// <summary>[US Core] The verification status to support the clinical status of the condition.</summary>
    [JsonPropertyName("verificationStatus")] public object? VerificationStatus { get; init; }

}
