// <auto-generated>
// HEDIS Core Coverage - Union of 3 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-coverage
//   - http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Coverage
//   - http://hl7.org/fhir/StructureDefinition/Coverage
// Generated at: 2026-03-13T03:00:24.4260985Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Coverage.
/// <para>Union of 3 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record Coverage
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Coverage";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>[HEDIS][CARIN-BB] The party who benefits from the insurance coverage; the patient when products and/or services are provided.</summary>
    [JsonPropertyName("beneficiary")] public ResourceReference? Beneficiary { get; init; }

    /// <summary>[CARIN-BB] A suite of underwriter specific classifiers.</summary>
    [JsonPropertyName("class")] public List<CoverageClassComponent>? Class { get; init; }

    /// <summary>[CARIN-BB] A unique identifier assigned to this coverage.</summary>
    [JsonPropertyName("identifier")] public List<Identifier>? Identifier { get; init; }

    /// <summary>[CARIN-BB] The program or plan underwriter or payor including both insurance and non-insurance agreements, such as patient-pay agreements.</summary>
    [JsonPropertyName("payor")] public List<object>? Payor { get; init; }

    /// <summary>[HEDIS][CARIN-BB]  Date that the contract became effective and Date that the contract was terminated or coverage changed.Time period during which the coverage is in force. A missing start date indicates the start date isn't known, a missing end date means the coverage is continuing to be in force.</summary>
    [JsonPropertyName("period")] public Period? Period { get; init; }

    /// <summary>[CARIN-BB] The relationship of beneficiary (patient) to the subscriber.</summary>
    [JsonPropertyName("relationship")] public object? Relationship { get; init; }

    /// <summary>[CARIN-BB] The status of the resource instance.</summary>
    [JsonPropertyName("status")] public string? Status { get; init; }

    /// <summary>[CARIN-BB] The insurer assigned ID for the Subscriber.</summary>
    [JsonPropertyName("subscriberId")] public object? SubscriberId { get; init; }

    /// <summary>[HEDIS][CARIN-BB] The type of coverage: social program, medical plan, accident coverage (workers compensation, auto), group health or payment by an individual or organization.</summary>
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }

}
