// <auto-generated>
// HEDIS Core DiagnosticReport - Union of 3 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-diagnosticreport-note
//   - http://hl7.org/fhir/us/core/StructureDefinition/us-core-diagnosticreport-note
//   - http://hl7.org/fhir/StructureDefinition/DiagnosticReport
// Generated at: 2026-03-13T03:00:24.4264321Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core DiagnosticReport.
/// <para>Union of 3 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record DiagnosticReport
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "DiagnosticReport";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>[US Core]  A code that classifies the clinical discipline, department or diagnostic service that created the report (e.g. cardiology, biochemistry, hematology, MRI). This is used for searching, sorting and display purposes.</summary>
    [JsonPropertyName("category")] public List<CodeableConcept>? Category { get; init; }

    /// <summary>[US Core] The test, panel, report, or note that was ordered.</summary>
    [JsonPropertyName("code")] public CodeableConcept? Code { get; init; }

    /// <summary>[US Core] This is the Datetime or Period when the report or note was written.</summary>
    [JsonPropertyName("effective")] public object? Effective { get; init; }

    /// <summary>[US Core] The healthcare event  (e.g. a patient and healthcare provider interaction) which this DiagnosticReport is about.</summary>
    [JsonPropertyName("encounter")] public ResourceReference? Encounter { get; init; }

    [JsonPropertyName("issued")] public string? Issued { get; init; }

    /// <summary>[US Core] The diagnostic service that is responsible for issuing the report.</summary>
    [JsonPropertyName("performer")] public List<object>? Performer { get; init; }

    /// <summary>[US Core] Rich text representation of the entire result as issued by the diagnostic service. Multiple formats are allowed but they SHALL be semantically equivalent.</summary>
    [JsonPropertyName("presentedForm")] public List<object>? PresentedForm { get; init; }

    /// <summary>[US Core] The status of the diagnostic report.</summary>
    [JsonPropertyName("status")] public string? Status { get; init; }

    /// <summary>[HEDIS][US Core] The subject of the report. Usually, but not always, this is a patient. However diagnostic services also perform analyses on specimens collected from a variety of other sources.</summary>
    [JsonPropertyName("subject")] public ResourceReference? Subject { get; init; }

}
