// <auto-generated>
// HEDIS Core DiagnosticReport - Union of 1 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-diagnosticreport-note
// Generated at: 2026-02-24T19:44:50.1197771Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core DiagnosticReport.
/// </summary>
public sealed record DiagnosticReport
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "DiagnosticReport";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")] public string? ImplicitRules { get; init; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")] public string? Language { get; init; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")] public Narrative? Text { get; init; }

    /// <summary>Contained, inline Resources.</summary>
    [JsonPropertyName("contained")] public List<object>? Contained { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")] public List<Extension>? ModifierExtension { get; init; }

    /// <summary>[US Core]  A code that classifies the clinical discipline, department or diagnostic service that created the report (e.g. cardiology, biochemistry, hematology, MRI). This is used for searching, sorting and display purposes.</summary>
    [JsonPropertyName("category")] public List<CodeableConcept>? Category { get; init; }

    /// <summary>[US Core] The test, panel, report, or note that was ordered.</summary>
    [JsonPropertyName("code")] public CodeableConcept? Code { get; init; }

    /// <summary>[US Core] This is the Datetime or Period when the report or note was written.</summary>
    [JsonPropertyName("effective")] public object? Effective { get; init; }

    /// <summary>[US Core] The healthcare event  (e.g. a patient and healthcare provider interaction) which this DiagnosticReport is about.</summary>
    [JsonPropertyName("encounter")] public ResourceReference? Encounter { get; init; }

    /// <summary>[US Core] The diagnostic service that is responsible for issuing the report.</summary>
    [JsonPropertyName("performer")] public List<object>? Performer { get; init; }

    /// <summary>[US Core] Rich text representation of the entire result as issued by the diagnostic service. Multiple formats are allowed but they SHALL be semantically equivalent.</summary>
    [JsonPropertyName("presentedForm")] public object? PresentedForm { get; init; }

    /// <summary>[US Core] The status of the diagnostic report.</summary>
    [JsonPropertyName("status")] public string? Status { get; init; }

    /// <summary>[HEDIS][US Core] The subject of the report. Usually, but not always, this is a patient. However diagnostic services also perform analyses on specimens collected from a variety of other sources.</summary>
    [JsonPropertyName("subject")] public ResourceReference? Subject { get; init; }

}
