// <auto-generated>
// HEDIS Core DocumentReference - Union of 1 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-documentreference
// Generated at: 2026-02-24T19:44:50.1204103Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core DocumentReference.
/// </summary>
public sealed record DocumentReference
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "DocumentReference";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")] public string? ImplicitRules { get; init; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")] public string? Language { get; init; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")] public Narrative? Text { get; init; }

    /// <summary>Contained, inline Resources.</summary>
    [JsonPropertyName("contained")] public List<object>? Contained { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")] public List<Extension>? ModifierExtension { get; init; }

    /// <summary>[US Core] Identifies who is responsible for adding the information to the document.</summary>
    [JsonPropertyName("author")] public List<ResourceReference>? Author { get; init; }

    /// <summary>[US Core] A categorization for the type of document referenced - helps for indexing and searching. This may be implied by or derived from the code specified in the DocumentReference.type.</summary>
    [JsonPropertyName("category")] public List<CodeableConcept>? Category { get; init; }

    /// <summary>[US Core] The document and format referenced. There may be multiple content element repetitions, each with a different format.</summary>
    [JsonPropertyName("content")] public List<ContentComponent>? Content { get; init; }

    /// <summary>[US Core] The clinical context in which the document was prepared.</summary>
    [JsonPropertyName("context")] public ContextComponent? Context { get; init; }

    /// <summary>[US Core] Identifies the organization or group who is responsible for ongoing maintenance of and access to the document.</summary>
    [JsonPropertyName("custodian")] public object? Custodian { get; init; }

    /// <summary>[US Core] When the document reference was created.</summary>
    [JsonPropertyName("date")] public object? Date { get; init; }

    /// <summary>[US Core] Other identifiers associated with the document, including version independent identifiers.</summary>
    [JsonPropertyName("identifier")] public List<Identifier>? Identifier { get; init; }

    /// <summary>[US Core] The status of this document reference.</summary>
    [JsonPropertyName("status")] public string? Status { get; init; }

    /// <summary>[HEDIS][US Core] Who or what the document is about. The document can be about a person, (patient or healthcare practitioner), a device (e.g. a machine) or even a group of subjects (such as a document about a herd of farm animals, or a set of patients that share a common exposure).</summary>
    [JsonPropertyName("subject")] public ResourceReference? Subject { get; init; }

    /// <summary>[US Core] Specifies the particular kind of document referenced  (e.g. History and Physical, Discharge Summary, Progress Note). This usually equates to the purpose of making the document referenced.</summary>
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }

}
