// <auto-generated>
// HEDIS Core Encounter - Union of 1 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-encounter
// Generated at: 2026-02-24T19:44:50.1213170Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Encounter.
/// </summary>
public sealed record Encounter
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Encounter";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")] public string? ImplicitRules { get; init; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")] public string? Language { get; init; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")] public Narrative? Text { get; init; }

    /// <summary>Contained, inline Resources.</summary>
    [JsonPropertyName("contained")] public List<object>? Contained { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")] public List<Extension>? ModifierExtension { get; init; }

    /// <summary>[US Core] Concepts representing classification of patient encounter such as ambulatory (outpatient), inpatient, emergency, home health or others due to local variations.</summary>
    [JsonPropertyName("class")] public List<object>? Class { get; init; }

    /// <summary>[HEDIS] The list of diagnosis relevant to this encounter.</summary>
    [JsonPropertyName("diagnosis")] public List<DiagnosisComponent>? Diagnosis { get; init; }

    /// <summary>[US Core] Details about the admission to a healthcare service.</summary>
    [JsonPropertyName("hospitalization")] public HospitalizationComponent? Hospitalization { get; init; }

    /// <summary>[US Core] Identifier(s) by which this encounter is known.</summary>
    [JsonPropertyName("identifier")] public List<Identifier>? Identifier { get; init; }

    /// <summary>[US Core] List of locations where  the patient has been during this encounter.</summary>
    [JsonPropertyName("location")] public List<LocationComponent>? Location { get; init; }

    /// <summary>[US Core] The list of people responsible for providing the service.</summary>
    [JsonPropertyName("participant")] public List<ParticipantComponent>? Participant { get; init; }

    /// <summary>[HEDIS][US Core] The start and end time of the encounter.</summary>
    [JsonPropertyName("period")] public Period? Period { get; init; }

    /// <summary>[US Core] Reason the encounter takes place, expressed as a code. For admissions, this can be used for a coded admission diagnosis.</summary>
    [JsonPropertyName("reasonCode")] public List<CodeableConcept>? ReasonCode { get; init; }

    /// <summary>[US Core] planned | arrived | triaged | in-progress | onleave | finished | cancelled +.</summary>
    [JsonPropertyName("status")] public string? Status { get; init; }

    /// <summary>The patient present at the encounter</summary>
    [JsonPropertyName("subject")] public ResourceReference? Subject { get; init; }

    /// <summary>[US Core] Specific type of encounter (e.g. e-mail consultation, surgical day-care, skilled nursing, rehabilitation).</summary>
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }

}
