// <auto-generated>
// HEDIS Core ExplanationOfBenefit - Union of 8 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-explanationofbenefit-inpatient-institutional
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-explanationofbenefit-outpatient-institutional
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-explanationofbenefit-pharmacy
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-explanationofbenefit-professional-nonclinician
//   - http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-ExplanationOfBenefit
//   - http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-ExplanationOfBenefit-Pharmacy
//   - http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-ExplanationOfBenefit-Professional-NonClinician
//   - http://hl7.org/fhir/StructureDefinition/ExplanationOfBenefit
// Generated at: 2026-03-13T03:00:24.4275557Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core ExplanationOfBenefit.
/// <para>Union of 8 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record ExplanationOfBenefit
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "ExplanationOfBenefit";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>[CARIN-BB] The adjudication results which are presented at the header level rather than at the line-item or add-item levels.</summary>
    [JsonPropertyName("adjudication")] public List<AdjudicationComponent>? Adjudication { get; init; }

    /// <summary>[CARIN-BB] The period for which charges are being submitted.</summary>
    [JsonPropertyName("billablePeriod")] public Period? BillablePeriod { get; init; }

    /// <summary>[CARIN-BB] The members of the team who provided the products and services.</summary>
    [JsonPropertyName("careTeam")] public List<CareTeamComponent>? CareTeam { get; init; }

    /// <summary>[CARIN-BB] The date this resource was created.</summary>
    [JsonPropertyName("created")] public object? Created { get; init; }

    /// <summary>[CARIN-BB] Information about diagnoses relevant to the claim items.</summary>
    [JsonPropertyName("diagnosis")] public List<DiagnosisComponent>? Diagnosis { get; init; }

    /// <summary>[CARIN-BB] A unique identifier assigned to this explanation of benefit.</summary>
    [JsonPropertyName("identifier")] public List<Identifier>? Identifier { get; init; }

    /// <summary>[CARIN-BB] Financial instruments for reimbursement for the health care products and services specified on the claim.</summary>
    [JsonPropertyName("insurance")] public List<InsuranceComponent>? Insurance { get; init; }

    /// <summary>[CARIN-BB] The party responsible for authorization, adjudication and reimbursement.</summary>
    [JsonPropertyName("insurer")] public ResourceReference? Insurer { get; init; }

    /// <summary>[HEDIS][CARIN-BB] A claim line. Either a simple (a product or service) or a 'group' of details which can also be a simple items or groups of sub-details.</summary>
    [JsonPropertyName("item")] public List<ItemComponent>? Item { get; init; }

    /// <summary>[CARIN-BB] The outcome of the claim, predetermination, or preauthorization processing.</summary>
    [JsonPropertyName("outcome")] public object? Outcome { get; init; }

    /// <summary>[HEDIS][CARIN-BB] The party to whom the professional services and/or products have been supplied or are being considered and for whom actual for forecast reimbursement is sought.</summary>
    [JsonPropertyName("patient")] public ResourceReference? Patient { get; init; }

    /// <summary>[CARIN-BB] The party to be reimbursed for cost of the products and services according to the terms of the policy.</summary>
    [JsonPropertyName("payee")] public PayeeComponent? Payee { get; init; }

    /// <summary>[CARIN-BB] Payment details for the adjudication of the claim.</summary>
    [JsonPropertyName("payment")] public PaymentComponent? Payment { get; init; }

    /// <summary>[CARIN-BB] Procedures performed on the patient relevant to the billing items with the claim.</summary>
    [JsonPropertyName("procedure")] public List<ProcedureComponent>? Procedure { get; init; }

    /// <summary>[CARIN-BB]  A note that describes or explains adjudication results in a human readable form.</summary>
    [JsonPropertyName("processNote")] public List<NoteComponent>? ProcessNote { get; init; }

    /// <summary>[CARIN-BB] The provider which is responsible for the claim, predetermination or preauthorization.</summary>
    [JsonPropertyName("provider")] public ResourceReference? Provider { get; init; }

    /// <summary>[CARIN-BB] Other claims which are related to this claim such as prior submissions or claims for related services or for the same event.</summary>
    [JsonPropertyName("related")] public List<RelatedClaimComponent>? Related { get; init; }

    /// <summary>[CARIN-BB] The status of the resource instance.</summary>
    [JsonPropertyName("status")] public string? Status { get; init; }

    /// <summary>[CARIN-BB] A finer grained suite of claim type codes which may convey additional information such as Inpatient vs Outpatient and/or a specialty service.</summary>
    [JsonPropertyName("subType")] public CodeableConcept? SubType { get; init; }

    /// <summary>[CARIN-BB] Additional information codes regarding exceptions, special considerations, the condition, situation, prior or concurrent issues.</summary>
    [JsonPropertyName("supportingInfo")] public List<SupportingInfoComponent>? SupportingInfo { get; init; }

    /// <summary>[CARIN-BB] Categorized monetary totals for the adjudication.</summary>
    [JsonPropertyName("total")] public List<TotalComponent>? Total { get; init; }

    /// <summary>[CARIN-BB] The category of claim, e.g. oral, pharmacy, vision, institutional, professional.</summary>
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }

    /// <summary>[CARIN-BB] A code to indicate whether the nature of the request is: to request adjudication of products and services previously rendered; or requesting authorization and adjudication for provision in the future; or requesting the non-binding adjudication of the listed products and services which could be provided in the future.</summary>
    [JsonPropertyName("use")] public object? Use { get; init; }

}
