// <auto-generated>
// HEDIS Core Immunization - Union of 3 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-immunization
//   - http://hl7.org/fhir/us/core/StructureDefinition/us-core-immunization
//   - http://hl7.org/fhir/StructureDefinition/Immunization
// Generated at: 2026-03-13T03:00:24.4278381Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Immunization.
/// <para>Union of 3 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record Immunization
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Immunization";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>[HEDIS][US Core] Date vaccine administered or was to be administered.</summary>
    [JsonPropertyName("occurrence")] public string? Occurrence { get; init; }

    /// <summary>[HEDIS] [US Core] The patient who either received or did not receive the immunization.</summary>
    [JsonPropertyName("patient")] public ResourceReference? Patient { get; init; }

    /// <summary>[US Core] An indication that the content of the record is based on information from the person who administered the vaccine. This reflects the context under which the data was originally recorded.</summary>
    [JsonPropertyName("primarySource")] public object? PrimarySource { get; init; }

    /// <summary>[US Core] Indicates the current status of the immunization event.</summary>
    [JsonPropertyName("status")] public string? Status { get; init; }

    /// <summary>[US Core] Indicates the reason the immunization event was not performed.</summary>
    [JsonPropertyName("statusReason")] public CodeableConcept? StatusReason { get; init; }

    /// <summary>[US Core] Vaccine that was administered or was to be administered.</summary>
    [JsonPropertyName("vaccineCode")] public object? VaccineCode { get; init; }

}
