// <auto-generated>
// HEDIS Core Location - Union of 1 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-location
// Generated at: 2026-02-24T19:44:50.1250986Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Location.
/// </summary>
public sealed record Location
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Location";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")] public string? ImplicitRules { get; init; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")] public string? Language { get; init; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")] public Narrative? Text { get; init; }

    /// <summary>Contained, inline Resources.</summary>
    [JsonPropertyName("contained")] public List<object>? Contained { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")] public List<Extension>? ModifierExtension { get; init; }

    /// <summary>[US Core] Physical location.</summary>
    [JsonPropertyName("address")] public List<Address>? Address { get; init; }

    [JsonPropertyName("identifier")] public List<Identifier>? Identifier { get; init; }

    /// <summary>[US Core] The organization responsible for the provisioning and upkeep of the location.</summary>
    [JsonPropertyName("managingOrganization")] public object? ManagingOrganization { get; init; }

    /// <summary>[US Core] Name of the location as used by humans. Does not need to be unique.</summary>
    [JsonPropertyName("name")] public List<HumanName>? Name { get; init; }

    /// <summary>[US Core] The contact details of communication devices available at the location. This can include phone numbers, fax numbers, mobile numbers, email addresses and web sites.</summary>
    [JsonPropertyName("telecom")] public List<ContactPoint>? Telecom { get; init; }

    /// <summary>[HEDIS] Indicates the type of function performed at the location.</summary>
    [JsonPropertyName("type")] public CodeableConcept? Type { get; init; }

}
