// <auto-generated>
// HEDIS Core Medication - Union of 1 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-medication
// Generated at: 2026-02-24T19:44:50.1260945Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Medication.
/// </summary>
public sealed record Medication
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Medication";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")] public string? ImplicitRules { get; init; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")] public string? Language { get; init; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")] public Narrative? Text { get; init; }

    /// <summary>Contained, inline Resources.</summary>
    [JsonPropertyName("contained")] public List<object>? Contained { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")] public List<Extension>? ModifierExtension { get; init; }

    /// <summary>[US Core] A code (or set of codes) that specify this medication, or a textual description if no code is available. Usage note: This could be a standard medication code such as a code from RxNorm, SNOMED CT, IDMP etc. It could also be a national or local formulary code, optionally with translations to other code systems.</summary>
    [JsonPropertyName("code")] public CodeableConcept? Code { get; init; }

}
