// <auto-generated>
// HEDIS Core MedicationAdministration - Union of 2 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-medicationadministration
//   - http://hl7.org/fhir/StructureDefinition/MedicationAdministration
// Generated at: 2026-03-13T03:00:24.4289501Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core MedicationAdministration.
/// <para>Union of 2 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record MedicationAdministration
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "MedicationAdministration";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>[HEDIS] A specific date/time or interval of time during which the administration took place (or did not take place, when the 'notGiven' attribute is true). For many administrations, such as swallowing a tablet the use of dateTime is more appropriate.</summary>
    [JsonPropertyName("effective")] public object? Effective { get; init; }

    /// <summary>[HEDIS] Identifies the medication that was administered. This is either a link to a resource representing the details of the medication or a simple attribute carrying a code that identifies the medication from a known list of medications.</summary>
    [JsonPropertyName("medication")] public CodeableConcept? Medication { get; init; }

    /// <summary>[HEDIS] Will generally be set to show that the administration has been completed.  For some long running administrations such as infusions, it is possible for an administration to be started but not completed or it may be paused while some other process is under way.</summary>
    [JsonPropertyName("status")] public string? Status { get; init; }

}
