// <auto-generated>
// HEDIS Core MedicationDispense - Union of 2 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-medicationdispense
//   - http://hl7.org/fhir/StructureDefinition/MedicationDispense
// Generated at: 2026-03-13T03:00:24.4293941Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core MedicationDispense.
/// <para>Union of 2 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record MedicationDispense
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "MedicationDispense";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>[HEDIS] The amount of medication expressed as a timing amount.</summary>
    [JsonPropertyName("daysSupply")] public object? DaysSupply { get; init; }

    /// <summary>[HEDIS] Identifies the medication being administered. This is either a link to a resource representing the details of the medication or a simple attribute carrying a code that identifies the medication from a known list of medications.</summary>
    [JsonPropertyName("medication")] public CodeableConcept? Medication { get; init; }

    [JsonPropertyName("quantity")] public object? Quantity { get; init; }

    /// <summary>[HEDIS] A code specifying the state of the set of dispense events.</summary>
    [JsonPropertyName("status")] public string? Status { get; init; }

    /// <summary>[HEDIS] The time the dispensed product was provided to the patient or their representative.</summary>
    [JsonPropertyName("whenHandedOver")] public object? WhenHandedOver { get; init; }

}
