// <auto-generated>
// HEDIS Core Medication - Union of 3 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-medication
//   - http://hl7.org/fhir/us/core/StructureDefinition/us-core-medication
//   - http://hl7.org/fhir/StructureDefinition/Medication
// Generated at: 2026-03-13T03:00:24.4285536Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Medication.
/// <para>Union of 3 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record Medication
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Medication";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>[US Core] A code (or set of codes) that specify this medication, or a textual description if no code is available. Usage note: This could be a standard medication code such as a code from RxNorm, SNOMED CT, IDMP etc. It could also be a national or local formulary code, optionally with translations to other code systems.</summary>
    [JsonPropertyName("code")] public CodeableConcept? Code { get; init; }

}
