// <auto-generated>
// HEDIS Core MedicationDispense - Union of 1 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-medicationdispense
// Generated at: 2026-02-24T19:44:50.1278695Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core MedicationDispense.
/// </summary>
public sealed record MedicationDispense
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "MedicationDispense";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")] public string? ImplicitRules { get; init; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")] public string? Language { get; init; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")] public Narrative? Text { get; init; }

    /// <summary>Contained, inline Resources.</summary>
    [JsonPropertyName("contained")] public List<object>? Contained { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")] public List<Extension>? ModifierExtension { get; init; }

    /// <summary>[HEDIS] The amount of medication expressed as a timing amount.</summary>
    [JsonPropertyName("daysSupply")] public object? DaysSupply { get; init; }

    /// <summary>[HEDIS] Identifies the medication being administered. This is either a link to a resource representing the details of the medication or a simple attribute carrying a code that identifies the medication from a known list of medications.</summary>
    [JsonPropertyName("medication")] public CodeableConcept? Medication { get; init; }

    [JsonPropertyName("quantity")] public object? Quantity { get; init; }

    /// <summary>[HEDIS] A code specifying the state of the set of dispense events.</summary>
    [JsonPropertyName("status")] public string? Status { get; init; }

    /// <summary>[HEDIS] A link to a resource representing the person or the group to whom the medication will be given.</summary>
    [JsonPropertyName("subject")] public ResourceReference? Subject { get; init; }

    /// <summary>[HEDIS] The time the dispensed product was provided to the patient or their representative.</summary>
    [JsonPropertyName("whenHandedOver")] public object? WhenHandedOver { get; init; }

}
