// <auto-generated>
// HEDIS Core Observation - Union of 6 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-laboratory-result-observation
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-observation-blood-pressure
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-observation-bmi
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-observation-vital-signs
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-observation
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-simple-observation
// Generated at: 2026-02-24T19:44:50.1287563Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Observation.
/// <para>Union of 6 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record Observation
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Observation";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")] public string? ImplicitRules { get; init; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")] public string? Language { get; init; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")] public Narrative? Text { get; init; }

    /// <summary>Contained, inline Resources.</summary>
    [JsonPropertyName("contained")] public List<object>? Contained { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")] public List<Extension>? ModifierExtension { get; init; }

    /// <summary>[US Core] A code that classifies the general type of observation being made.</summary>
    [JsonPropertyName("category")] public List<CodeableConcept>? Category { get; init; }

    /// <summary>[US Core] The test that was performed.  A LOINC **SHALL** be used if the concept is present in LOINC.</summary>
    [JsonPropertyName("code")] public CodeableConcept? Code { get; init; }

    /// <summary>[US Core] Some observations have multiple component observations.  These component observations are expressed as separate code value pairs that share the same attributes.  Examples include systolic and diastolic component observations for blood pressure measurement and multiple component observations for genetics observations.</summary>
    [JsonPropertyName("component")] public List<ObservationComponent>? Component { get; init; }

    /// <summary>[US Core] Provides a reason why the expected value in the element Observation.value[x] is missing.</summary>
    [JsonPropertyName("dataAbsentReason")] public CodeableConcept? DataAbsentReason { get; init; }

    /// <summary>Related Observation(s) or other resource the observation is made from</summary>
    [JsonPropertyName("derivedFrom")] public ResourceReference? DerivedFrom { get; init; }

    /// <summary>[HEDIS][US Core] For lab tests this is the specimen collection date.  For Ask at Order Entry Questions (AOE)'s this is the date the question was asked.</summary>
    [JsonPropertyName("effective")] public object? Effective { get; init; }

    /// <summary>[HEDIS][US Core] Who was responsible for asserting the observed value as "true".</summary>
    [JsonPropertyName("performer")] public List<ResourceReference>? Performer { get; init; }

    /// <summary>[US Core] The status of the result value.</summary>
    [JsonPropertyName("status")] public string? Status { get; init; }

    /// <summary>[HEDIS][US Core] The patient, or group of patients, location, or device this observation is about and into whose record the observation is placed. If the actual focus of the observation is different from the subject (or a sample of, part, or region of the subject), the `focus` element or the `code` itself specifies the actual focus of the observation.</summary>
    [JsonPropertyName("subject")] public ResourceReference? Subject { get; init; }

    /// <summary>[US Core] The Laboratory result value.  If a coded value,  the valueCodeableConcept.code **SHOULD**  be selected from [SNOMED CT](http://hl7.org/fhir/ValueSet/uslab-obs-codedresults).  If a numeric value, valueQuantity.code **SHALL** be selected from [UCUM](http://unitsofmeasure.org).  A FHIR [UCUM Codes value set](http://hl7.org/fhir/STU3/valueset-ucum-units.html) that defines all UCUM codes is in the FHIR specification.</summary>
    [JsonPropertyName("value")] public object? Value { get; init; }

}
