// <auto-generated>
// HEDIS Core Organization - Union of 4 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-organization
//   - http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Organization
//   - http://hl7.org/fhir/us/core/StructureDefinition/us-core-organization
//   - http://hl7.org/fhir/StructureDefinition/Organization
// Generated at: 2026-03-13T03:00:24.4302624Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Organization.
/// <para>Union of 4 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record Organization
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Organization";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    [JsonPropertyName("active")] public bool? Active { get; init; }

    [JsonPropertyName("address")] public List<Address>? Address { get; init; }

    /// <summary>[CARIN-BB] Identifier for the organization that is used to identify the organization across multiple disparate systems.</summary>
    [JsonPropertyName("identifier")] public List<Identifier>? Identifier { get; init; }

    [JsonPropertyName("name")] public string? Name { get; init; }

    [JsonPropertyName("telecom")] public List<ContactPoint>? Telecom { get; init; }

}
