// <auto-generated>
// HEDIS Core Patient - Union of 1 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-patient
// Generated at: 2026-02-24T19:44:50.1311006Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Patient.
/// </summary>
public sealed record Patient
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Patient";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")] public string? ImplicitRules { get; init; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")] public string? Language { get; init; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")] public Narrative? Text { get; init; }

    /// <summary>Contained, inline Resources.</summary>
    [JsonPropertyName("contained")] public List<object>? Contained { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")] public List<Extension>? ModifierExtension { get; init; }

    /// <summary>[US Core] An address for the individual.</summary>
    [JsonPropertyName("address")] public List<Address>? Address { get; init; }

    /// <summary>[HEDIS][US Core]  The date of birth for the individual.</summary>
    [JsonPropertyName("birthDate")] public string? BirthDate { get; init; }

    /// <summary>[US Core] A language which may be used to communicate with the patient about his or her health.</summary>
    [JsonPropertyName("communication")] public List<CommunicationComponent>? Communication { get; init; }

    /// <summary>[CARIN-BB][HEDIS]   Indicates if the individual is deceased or not.</summary>
    [JsonPropertyName("deceased")] public string? Deceased { get; init; }

    /// <summary>[US Core] Administrative Gender - the gender that the patient is considered to have for administration and record keeping purposes.</summary>
    [JsonPropertyName("gender")] public string? Gender { get; init; }

    /// <summary>[CARIN BB] An identifier for this patient.</summary>
    [JsonPropertyName("identifier")] public List<Identifier>? Identifier { get; init; }

    /// <summary>[US Core] A name associated with the individual.</summary>
    [JsonPropertyName("name")] public List<HumanName>? Name { get; init; }

    /// <summary>[US Core] A contact detail (e.g. a telephone number or an email address) by which the individual may be contacted.</summary>
    [JsonPropertyName("telecom")] public List<ContactPoint>? Telecom { get; init; }

}
