// <auto-generated>
// HEDIS Core Practitioner - Union of 4 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-practitioner
//   - http://hl7.org/fhir/us/carin-bb/StructureDefinition/C4BB-Practitioner
//   - http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitioner
//   - http://hl7.org/fhir/StructureDefinition/Practitioner
// Generated at: 2026-03-13T03:00:24.4318962Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Practitioner.
/// <para>Union of 4 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record Practitioner
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Practitioner";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>[US Core] An identifier that applies to this person in this role.</summary>
    [JsonPropertyName("identifier")] public List<Identifier>? Identifier { get; init; }

    /// <summary>[US Core] The name(s) associated with the practitioner.</summary>
    [JsonPropertyName("name")] public List<HumanName>? Name { get; init; }

}
