// <auto-generated>
// HEDIS Core PractitionerRole - Union of 1 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-practitionerrole
// Generated at: 2026-02-24T19:44:50.1334225Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core PractitionerRole.
/// </summary>
public sealed record PractitionerRole
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "PractitionerRole";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")] public string? ImplicitRules { get; init; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")] public string? Language { get; init; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")] public Narrative? Text { get; init; }

    /// <summary>Contained, inline Resources.</summary>
    [JsonPropertyName("contained")] public List<object>? Contained { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")] public List<Extension>? ModifierExtension { get; init; }

    /// <summary>[US Core] Roles which this practitioner is authorized to perform for the organization.</summary>
    [JsonPropertyName("code")] public CodeableConcept? Code { get; init; }

    /// <summary>[US Core] Technical endpoints providing access to services operated for the practitioner with this role.</summary>
    [JsonPropertyName("endpoint")] public object? Endpoint { get; init; }

    /// <summary>[US Core] The location(s) at which this practitioner provides care.</summary>
    [JsonPropertyName("location")] public List<object>? Location { get; init; }

    /// <summary>[US Core] The organization where the Practitioner performs the roles associated.</summary>
    [JsonPropertyName("organization")] public object? Organization { get; init; }

    [JsonPropertyName("period")] public Period? Period { get; init; }

    /// <summary>[US Core] Practitioner that is able to provide the defined services for the organization.</summary>
    [JsonPropertyName("practitioner")] public object? Practitioner { get; init; }

    /// <summary>[US Core] Specific specialty of the practitioner.</summary>
    [JsonPropertyName("specialty")] public object? Specialty { get; init; }

    /// <summary>[US Core] Contact details that are specific to the role/location/service.</summary>
    [JsonPropertyName("telecom")] public List<ContactPoint>? Telecom { get; init; }

}
