// <auto-generated>
// HEDIS Core Procedure - Union of 3 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-procedure
//   - http://hl7.org/fhir/us/core/StructureDefinition/us-core-procedure
//   - http://hl7.org/fhir/StructureDefinition/Procedure
// Generated at: 2026-03-13T03:00:24.4335327Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core Procedure.
/// <para>Union of 3 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record Procedure
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "Procedure";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>[HEDIS] Detailed and structured anatomical location information. Multiple locations are allowed - e.g. multiple punch biopsies of a lesion.</summary>
    [JsonPropertyName("bodySite")] public List<CodeableConcept>? BodySite { get; init; }

    /// <summary>[US Core] The specific procedure that is performed. Use text if the exact nature of the procedure cannot be coded (e.g. "Laparoscopic Appendectomy").</summary>
    [JsonPropertyName("code")] public CodeableConcept? Code { get; init; }

    /// <summary>[US Core] Estimated or actual date, date-time, period, or age when the procedure was performed.  Allows a period to support complex procedures that span more than one date, and also allows for the length of the procedure to be captured.</summary>
    [JsonPropertyName("performed")] public object? Performed { get; init; }

    /// <summary>[US Core] A code specifying the state of the procedure. Generally, this will be the in-progress or completed state.</summary>
    [JsonPropertyName("status")] public string? Status { get; init; }

    /// <summary>[HEDIS][US Core] The person, animal or group on which the procedure was performed.</summary>
    [JsonPropertyName("subject")] public ResourceReference? Subject { get; init; }

}
