// <auto-generated>
// HEDIS Core QuestionnaireResponse - Union of 1 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-questionnaireresponse
// Generated at: 2026-02-24T19:44:50.1358680Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core QuestionnaireResponse.
/// </summary>
public sealed record QuestionnaireResponse
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "QuestionnaireResponse";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")] public string? ImplicitRules { get; init; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")] public string? Language { get; init; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")] public Narrative? Text { get; init; }

    /// <summary>Contained, inline Resources.</summary>
    [JsonPropertyName("contained")] public List<object>? Contained { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")] public List<Extension>? ModifierExtension { get; init; }

    /// <summary>[HEDIS][US Core] Person who received the answers to the questions in the QuestionnaireResponse and recorded them in the system.</summary>
    [JsonPropertyName("author")] public List<ResourceReference>? Author { get; init; }

    /// <summary>[US Core] The date and/or time that this set of answers were last changed.</summary>
    [JsonPropertyName("authored")] public object? Authored { get; init; }

    /// <summary>[US Core] A business identifier assigned to a particular completed (or partially completed) questionnaire.</summary>
    [JsonPropertyName("identifier")] public List<Identifier>? Identifier { get; init; }

    /// <summary>[US Core] A group or question item from the original questionnaire for which answers are provided.</summary>
    [JsonPropertyName("item")] public List<ItemComponent>? Item { get; init; }

    /// <summary>[US Core] The Questionnaire that defines and organizes the questions for which answers are being provided.</summary>
    [JsonPropertyName("questionnaire")] public string? Questionnaire { get; init; }

    /// <summary>[US Core] The position of the questionnaire response within its overall lifecycle.</summary>
    [JsonPropertyName("status")] public string? Status { get; init; }

    /// <summary>[HEDIS][US Core] The subject of the questionnaire response.  This could be a patient, organization, practitioner, device, etc.  This is who/what the answers apply to, but is not necessarily the source of information.</summary>
    [JsonPropertyName("subject")] public ResourceReference? Subject { get; init; }

}
