// <auto-generated>
// HEDIS Core RelatedPerson - Union of 1 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-relatedperson
// Generated at: 2026-02-24T19:44:50.1366790Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core RelatedPerson.
/// </summary>
public sealed record RelatedPerson
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "RelatedPerson";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")] public string? ImplicitRules { get; init; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")] public string? Language { get; init; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")] public Narrative? Text { get; init; }

    /// <summary>Contained, inline Resources.</summary>
    [JsonPropertyName("contained")] public List<object>? Contained { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")] public List<Extension>? ModifierExtension { get; init; }

    /// <summary>[US Core] Whether this related person record is in active use.</summary>
    [JsonPropertyName("active")] public object? Active { get; init; }

    /// <summary>[US Core] Address where the related person can be contacted or visited.</summary>
    [JsonPropertyName("address")] public List<Address>? Address { get; init; }

    /// <summary>[US Core]  A name associated with the person.</summary>
    [JsonPropertyName("name")] public List<HumanName>? Name { get; init; }

    /// <summary>[HEDIS] The patient this person is related to.</summary>
    [JsonPropertyName("patient")] public ResourceReference? Patient { get; init; }

    /// <summary>[US Core] The nature of the relationship between a patient and the related person.</summary>
    [JsonPropertyName("relationship")] public object? Relationship { get; init; }

    /// <summary>[US Core] A contact detail for the person, e.g. a telephone number or an email address.</summary>
    [JsonPropertyName("telecom")] public List<ContactPoint>? Telecom { get; init; }

}
