// <auto-generated>
// HEDIS Core RelatedPerson - Union of 2 profile(s).
//   - https://ncqa.org/fhir/StructureDefinition/hedis-core-relatedperson
//   - http://hl7.org/fhir/StructureDefinition/RelatedPerson
// Generated at: 2026-03-13T03:00:24.4350603Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// HEDIS Core RelatedPerson.
/// <para>Union of 2 HEDIS profiles for this resource type.</para>
/// </summary>
public sealed record RelatedPerson
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")] public string ResourceType { get; init; } = "RelatedPerson";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")] public string? Id { get; init; }

    /// <summary>Metadata about the resource.</summary>
    [JsonPropertyName("meta")] public Meta? Meta { get; init; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")] public List<Extension>? Extension { get; init; }

    /// <summary>[US Core] Whether this related person record is in active use.</summary>
    [JsonPropertyName("active")] public object? Active { get; init; }

    /// <summary>[US Core] Address where the related person can be contacted or visited.</summary>
    [JsonPropertyName("address")] public List<Address>? Address { get; init; }

    /// <summary>[US Core]  A name associated with the person.</summary>
    [JsonPropertyName("name")] public List<HumanName>? Name { get; init; }

    /// <summary>[HEDIS] The patient this person is related to.</summary>
    [JsonPropertyName("patient")] public ResourceReference? Patient { get; init; }

    /// <summary>[US Core] The nature of the relationship between a patient and the related person.</summary>
    [JsonPropertyName("relationship")] public List<object>? Relationship { get; init; }

    /// <summary>[US Core] A contact detail for the person, e.g. a telephone number or an email address.</summary>
    [JsonPropertyName("telecom")] public List<ContactPoint>? Telecom { get; init; }

}
