<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Ncqa.Hedis.Core.Benchmarks</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ncqa.Hedis.Core\Ncqa.Hedis.Core.csproj" />
    <ProjectReference Include="..\src\Hl7.Fhir.R4\Hl7.Fhir.R4.csproj" />
  </ItemGroup>

</Project>
