// <auto-generated>
// Polymorphic JSON converters for HEDIS FHIR resources.
// Generated at: 2026-03-13T03:00:24.4375376Z
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core;

/// <summary>
/// Polymorphic JSON converter for a single FHIR resource.
/// Reads the <c>resourceType</c> discriminator and deserializes to the
/// matching HEDIS DTO. Unknown types are preserved as <see cref="JsonElement"/>.
/// </summary>
public sealed class HedisResourceConverter : JsonConverter<object>
{
    public override object? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Null)
            return null;

        // Copy the reader (Utf8JsonReader is a value type) to scan for resourceType
        // without consuming the original. This avoids building a JsonDocument DOM
        // (one full allocation per resource entry) and lets us deserialize with a
        // single forward pass via JsonSerializer.Deserialize<T>(ref reader, options).
        var scanReader = reader;
        var resourceType = ScanForResourceType(ref scanReader);

        return resourceType switch
        {
            "Bundle"                   => JsonSerializer.Deserialize<Bundle>(ref reader, options),
            "Claim"                    => JsonSerializer.Deserialize<Claim>(ref reader, options),
            "ClaimResponse"            => JsonSerializer.Deserialize<ClaimResponse>(ref reader, options),
            "Condition"                => JsonSerializer.Deserialize<Condition>(ref reader, options),
            "Coverage"                 => JsonSerializer.Deserialize<Coverage>(ref reader, options),
            "DiagnosticReport"         => JsonSerializer.Deserialize<DiagnosticReport>(ref reader, options),
            "DocumentReference"        => JsonSerializer.Deserialize<DocumentReference>(ref reader, options),
            "Encounter"                => JsonSerializer.Deserialize<Encounter>(ref reader, options),
            "ExplanationOfBenefit"     => JsonSerializer.Deserialize<ExplanationOfBenefit>(ref reader, options),
            "Immunization"             => JsonSerializer.Deserialize<Immunization>(ref reader, options),
            "Location"                 => JsonSerializer.Deserialize<Location>(ref reader, options),
            "Medication"               => JsonSerializer.Deserialize<Medication>(ref reader, options),
            "MedicationAdministration" => JsonSerializer.Deserialize<MedicationAdministration>(ref reader, options),
            "MedicationDispense"       => JsonSerializer.Deserialize<MedicationDispense>(ref reader, options),
            "Observation"              => JsonSerializer.Deserialize<Observation>(ref reader, options),
            "Organization"             => JsonSerializer.Deserialize<Organization>(ref reader, options),
            "Patient"                  => JsonSerializer.Deserialize<Patient>(ref reader, options),
            "Practitioner"             => JsonSerializer.Deserialize<Practitioner>(ref reader, options),
            "PractitionerRole"         => JsonSerializer.Deserialize<PractitionerRole>(ref reader, options),
            "Procedure"                => JsonSerializer.Deserialize<Procedure>(ref reader, options),
            "QuestionnaireResponse"    => JsonSerializer.Deserialize<QuestionnaireResponse>(ref reader, options),
            "RelatedPerson"            => JsonSerializer.Deserialize<RelatedPerson>(ref reader, options),
                                     _ => JsonSerializer.Deserialize<JsonElement>(ref reader, options)
        };
    }

    /// <summary>
    /// Scans a copy of the reader for the top-level <c>resourceType</c> property
    /// without advancing the original reader. Only examines depth-1 tokens so
    /// nested objects are skipped efficiently.
    /// </summary>
    private static string? ScanForResourceType(ref Utf8JsonReader reader)
    {
        int startDepth = reader.CurrentDepth;
        while (reader.Read())
        {
            if (reader.CurrentDepth == startDepth + 1 &&
                reader.TokenType == JsonTokenType.PropertyName &&
                reader.ValueTextEquals("resourceType"u8))
            {
                return reader.Read() ? reader.GetString() : null;
            }
        }
        return null;
    }

    public override void Write(Utf8JsonWriter writer, object value, JsonSerializerOptions options)
        => JsonSerializer.Serialize(writer, value, value.GetType(), options);
}

/// <summary>
/// Polymorphic JSON converter for a <see cref="List{T}"/> of FHIR resources.
/// Used on the <c>contained</c> property of domain resources.
/// Delegates each element to <see cref="HedisResourceConverter"/>.
/// </summary>
public sealed class HedisResourceListConverter : JsonConverter<List<object>>
{
    private static readonly HedisResourceConverter ItemConverter = new();

    public override List<object>? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Null) return null;
        if (reader.TokenType != JsonTokenType.StartArray)
            throw new JsonException($"Expected StartArray, got {reader.TokenType}");

        var list = new List<object>();
        while (reader.Read() && reader.TokenType != JsonTokenType.EndArray)
        {
            var item = ItemConverter.Read(ref reader, typeof(object), options);
            if (item != null) list.Add(item);
        }
        return list;
    }

    public override void Write(Utf8JsonWriter writer, List<object> value, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        foreach (var item in value)
            ItemConverter.Write(writer, item, options);
        writer.WriteEndArray();
    }
}
