// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-claim-inpatient-institutional
// Generated at: 2026-02-23T20:22:48.8033932Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core Claim DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-claim-inpatient-institutional</para>
/// </summary>
public sealed class HEDISCoreClaimInpatientInstitutional
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; set; } = "Claim";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>[HEDIS][CARIN-BB] The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; set; }

    /// <summary>[CARIN-BB] The category of claim, e.g. oral, pharmacy, vision, institutional, professional.</summary>
    [JsonPropertyName("type")]
    public ClaimInpatientInstitutionalTypeComponent? Type { get; set; }

    /// <summary>[CARIN-BB] A finer grained suite of claim type codes which may convey additional information such as Inpatient vs Outpatient and/or a specialty service.</summary>
    [JsonPropertyName("subType")]
    public ClaimInpatientInstitutionalSubTypeComponent? SubType { get; set; }

    /// <summary>[HEDIS] The party to whom the professional services and/or products have been supplied or are being considered and for whom actual or forecast reimbursement is sought.</summary>
    [JsonPropertyName("patient")]
    public ResourceReference? Patient { get; set; }

    /// <summary>[CARIN-BB] The period for which charges are being submitted.</summary>
    [JsonPropertyName("billablePeriod")]
    public ClaimInpatientInstitutionalBillablePeriodComponent? BillablePeriod { get; set; }

    /// <summary>[CARIN-BB] The members of the team who provided the products and services.</summary>
    [JsonPropertyName("careTeam")]
    public ClaimInpatientInstitutionalCareTeamComponent? CareTeam { get; set; }

    /// <summary>[CARIN-BB] Additional information codes regarding exceptions, special considerations, the condition, situation, prior or concurrent issues.</summary>
    [JsonPropertyName("supportingInfo")]
    public ClaimInpatientInstitutionalSupportingInfoComponent? SupportingInfo { get; set; }

    /// <summary>[CARIN-BB] Information about diagnoses relevant to the claim items.</summary>
    [JsonPropertyName("diagnosis")]
    public ClaimInpatientInstitutionalDiagnosisComponent? Diagnosis { get; set; }

    /// <summary>[CARIN-BB] Procedures performed on the patient relevant to the billing items with the claim.</summary>
    [JsonPropertyName("procedure")]
    public ClaimInpatientInstitutionalProcedureComponent? Procedure { get; set; }

    /// <summary>[HEDIS][CARIN-BB] A claim line. Either a simple  product or service or a 'group' of details which can each be a simple items or groups of sub-details.</summary>
    [JsonPropertyName("item")]
    public ClaimInpatientInstitutionalItemComponent? Item { get; set; }

}

/// <summary>
/// Component class for Claim.meta
/// </summary>
public sealed class ClaimInpatientInstitutionalMetaComponent
{
    /// <summary>[HEDIS] Tags applied to this resource. Tags are intended to be used to identify and relate resources to process and workflow, and applications are not required to consider the tags when interpreting the meaning of a resource.</summary>
    [JsonPropertyName("tag")]
    public object? Tag { get; set; }

}

/// <summary>
/// Component class for Claim.type
/// </summary>
public sealed class ClaimInpatientInstitutionalTypeComponent
{
    [JsonPropertyName("coding")]
    public object? Coding { get; set; }

}

/// <summary>
/// Component class for Claim.subType
/// </summary>
public sealed class ClaimInpatientInstitutionalSubTypeComponent
{
    [JsonPropertyName("coding")]
    public object? Coding { get; set; }

}

/// <summary>
/// Component class for Claim.billablePeriod
/// </summary>
public sealed class ClaimInpatientInstitutionalBillablePeriodComponent
{
    [JsonPropertyName("start")]
    public object? Start { get; set; }

    [JsonPropertyName("end")]
    public object? End { get; set; }

}

/// <summary>
/// Component class for Claim.careTeam
/// </summary>
public sealed class ClaimInpatientInstitutionalCareTeamComponent
{
    /// <summary>[HEDIS] A number to uniquely identify care team entries.</summary>
    [JsonPropertyName("sequence")]
    public object? Sequence { get; set; }

    /// <summary>[HEDIS][CARIN-BB] Member of the team who provided the product or service.</summary>
    [JsonPropertyName("provider")]
    public ResourceReference? Provider { get; set; }

}

/// <summary>
/// Component class for Claim.supportingInfo
/// </summary>
public sealed class ClaimInpatientInstitutionalSupportingInfoComponent
{
    /// <summary>[CARIN-BB] The general class of the information supplied: information; exception; accident, employment; onset, etc.</summary>
    [JsonPropertyName("category")]
    public object? Category { get; set; }

    [JsonPropertyName("timing")]
    public object? Timing { get; set; }

    [JsonPropertyName("value")]
    public object? Value { get; set; }

    [JsonPropertyName("code")]
    public object? Code { get; set; }

}

/// <summary>
/// Component class for Claim.diagnosis
/// </summary>
public sealed class ClaimInpatientInstitutionalDiagnosisComponent
{
    /// <summary>[HEDIS] A number to uniquely identify diagnosis entries.</summary>
    [JsonPropertyName("sequence")]
    public object? Sequence { get; set; }

    /// <summary>[CARIN-BB] The nature of illness or problem in a coded form or as a reference to an external defined Condition.</summary>
    [JsonPropertyName("diagnosis")]
    public CodeableConcept? Diagnosis { get; set; }

    /// <summary>[CARIN-BB] When the condition was observed or the relative ranking.</summary>
    [JsonPropertyName("type")]
    public object? Type { get; set; }

}

/// <summary>
/// Component class for Claim.procedure
/// </summary>
public sealed class ClaimInpatientInstitutionalProcedureComponent
{
    /// <summary>[HEDIS] A number to uniquely identify procedure entries.</summary>
    [JsonPropertyName("sequence")]
    public object? Sequence { get; set; }

    /// <summary>[CARIN-BB] The code or reference to a Procedure resource which identifies the clinical intervention performed.</summary>
    [JsonPropertyName("procedure")]
    public CodeableConcept? Procedure { get; set; }

}

/// <summary>
/// Component class for Claim.item
/// </summary>
public sealed class ClaimInpatientInstitutionalItemComponent
{
    /// <summary>[CARIN-BB] A number to uniquely identify item entries.</summary>
    [JsonPropertyName("sequence")]
    public object? Sequence { get; set; }

    /// <summary>[HEDIS] Diagnosis applicable for this service or product.</summary>
    [JsonPropertyName("diagnosisSequence")]
    public object? DiagnosisSequence { get; set; }

    /// <summary>[HEDIS] Procedures applicable for this service or product.</summary>
    [JsonPropertyName("procedureSequence")]
    public object? ProcedureSequence { get; set; }

    /// <summary>[HEDIS] Exceptions, special conditions and supporting information applicable for this service or product.</summary>
    [JsonPropertyName("informationSequence")]
    public object? InformationSequence { get; set; }

    /// <summary>[CARIN-BB] The type of revenue or cost center providing the product and/or service.</summary>
    [JsonPropertyName("revenue")]
    public object? Revenue { get; set; }

    /// <summary>[CARIN-BB] When the value is a group code then this item collects a set of related claim details, otherwise this contains the product, service, drug or other billing code for the item.</summary>
    [JsonPropertyName("productOrService")]
    public object? ProductOrService { get; set; }

    /// <summary>[CARIN-BB] Item typification or modifiers codes to convey additional context for the product or service.</summary>
    [JsonPropertyName("modifier")]
    public object? Modifier { get; set; }

    /// <summary>[HEDIS] The date or dates when the service or product was supplied, performed or completed.</summary>
    [JsonPropertyName("serviced")]
    public object? Serviced { get; set; }

    /// <summary>[CARIN-BB] The number of repetitions of a service or product.</summary>
    [JsonPropertyName("quantity")]
    public object? Quantity { get; set; }

}
