// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-explanationofbenefit-pharmacy
// Generated at: 2026-02-23T20:22:48.8852383Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core ExplanationOfBenefit DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-explanationofbenefit-pharmacy</para>
/// </summary>
public sealed class HEDISCoreExplanationOfBenefitPharmacy
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; set; } = "ExplanationOfBenefit";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>[HEDIS][CARIN-BB] The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; set; }

    /// <summary>[CARIN-BB] A unique identifier assigned to this explanation of benefit.</summary>
    [JsonPropertyName("identifier")]
    public ExplanationOfBenefitPharmacyIdentifierComponent? Identifier { get; set; }

    /// <summary>[CARIN-BB] The status of the resource instance.</summary>
    [JsonPropertyName("status")]
    public object? Status { get; set; }

    /// <summary>[CARIN-BB] The category of claim, e.g. oral, pharmacy, vision, institutional, professional.</summary>
    [JsonPropertyName("type")]
    public ExplanationOfBenefitPharmacyTypeComponent? Type { get; set; }

    /// <summary>[CARIN-BB] A code to indicate whether the nature of the request is: to request adjudication of products and services previously rendered; or requesting authorization and adjudication for provision in the future; or requesting the non-binding adjudication of the listed products and services which could be provided in the future.</summary>
    [JsonPropertyName("use")]
    public object? Use { get; set; }

    /// <summary>[HEDIS][CARIN-BB] The party to whom the professional services and/or products have been supplied or are being considered and for whom actual for forecast reimbursement is sought.</summary>
    [JsonPropertyName("patient")]
    public ResourceReference? Patient { get; set; }

    /// <summary>[CARIN-BB] The period for which charges are being submitted.</summary>
    [JsonPropertyName("billablePeriod")]
    public object? BillablePeriod { get; set; }

    /// <summary>[CARIN-BB] The date this resource was created.</summary>
    [JsonPropertyName("created")]
    public object? Created { get; set; }

    /// <summary>[CARIN-BB] The party responsible for authorization, adjudication and reimbursement.</summary>
    [JsonPropertyName("insurer")]
    public object? Insurer { get; set; }

    /// <summary>[CARIN-BB] Other claims which are related to this claim such as prior submissions or claims for related services or for the same event.</summary>
    [JsonPropertyName("related")]
    public ExplanationOfBenefitPharmacyRelatedComponent? Related { get; set; }

    /// <summary>[CARIN-BB] The party to be reimbursed for cost of the products and services according to the terms of the policy.</summary>
    [JsonPropertyName("payee")]
    public ExplanationOfBenefitPharmacyPayeeComponent? Payee { get; set; }

    /// <summary>[CARIN-BB] The outcome of the claim, predetermination, or preauthorization processing.</summary>
    [JsonPropertyName("outcome")]
    public object? Outcome { get; set; }

    /// <summary>[CARIN-BB] The members of the team who provided the products and services.</summary>
    [JsonPropertyName("careTeam")]
    public ExplanationOfBenefitPharmacyCareTeamComponent? CareTeam { get; set; }

    /// <summary>[CARIN-BB] Additional information codes regarding exceptions, special considerations, the condition, situation, prior or concurrent issues.</summary>
    [JsonPropertyName("supportingInfo")]
    public ExplanationOfBenefitPharmacySupportingInfoComponent? SupportingInfo { get; set; }

    /// <summary>[CARIN-BB] Financial instruments for reimbursement for the health care products and services specified on the claim.</summary>
    [JsonPropertyName("insurance")]
    public ExplanationOfBenefitPharmacyInsuranceComponent? Insurance { get; set; }

    /// <summary>[HEDIS][CARIN-BB] A claim line. Either a simple (a product or service) or a 'group' of details which can also be a simple items or groups of sub-details.</summary>
    [JsonPropertyName("item")]
    public ExplanationOfBenefitPharmacyItemComponent? Item { get; set; }

    /// <summary>[CARIN] Categorized monetary totals for the adjudication.</summary>
    [JsonPropertyName("total")]
    public object? Total { get; set; }

    /// <summary>[CARIN-BB] Payment details for the adjudication of the claim.</summary>
    [JsonPropertyName("payment")]
    public ExplanationOfBenefitPharmacyPaymentComponent? Payment { get; set; }

    /// <summary>[CARIN-BB] A note that describes or explains adjudication results in a human readable form.</summary>
    [JsonPropertyName("processNote")]
    public ExplanationOfBenefitPharmacyProcessNoteComponent? ProcessNote { get; set; }

}

/// <summary>
/// Component class for ExplanationOfBenefit.meta
/// </summary>
public sealed class ExplanationOfBenefitPharmacyMetaComponent
{
    /// <summary>[CARIN-BB] When the resource last changed - e.g. when the version changed.</summary>
    [JsonPropertyName("lastUpdated")]
    public object? LastUpdated { get; set; }

    [JsonPropertyName("profile")]
    public object? Profile { get; set; }

}

/// <summary>
/// Component class for ExplanationOfBenefit.identifier
/// </summary>
public sealed class ExplanationOfBenefitPharmacyIdentifierComponent
{
    /// <summary>[CARIN-BB] A coded type for the identifier that can be used to determine which identifier to use for a specific purpose.</summary>
    [JsonPropertyName("type")]
    public object? Type { get; set; }

    [JsonPropertyName("value")]
    public object? Value { get; set; }

}

/// <summary>
/// Component class for ExplanationOfBenefit.type
/// </summary>
public sealed class ExplanationOfBenefitPharmacyTypeComponent
{
    [JsonPropertyName("coding")]
    public object? Coding { get; set; }

}

/// <summary>
/// Component class for ExplanationOfBenefit.related
/// </summary>
public sealed class ExplanationOfBenefitPharmacyRelatedComponent
{
    /// <summary>[CARIN-BB] A code to convey how the claims are related.</summary>
    [JsonPropertyName("relationship")]
    public object? Relationship { get; set; }

    /// <summary>[CARIN-BB] An alternate organizational reference to the case or file to which this particular claim pertains.</summary>
    [JsonPropertyName("reference")]
    public object? Reference { get; set; }

}

/// <summary>
/// Component class for ExplanationOfBenefit.payee
/// </summary>
public sealed class ExplanationOfBenefitPharmacyPayeeComponent
{
    /// <summary>[CARIN-BB] Type of Party to be reimbursed: Subscriber, provider, other.</summary>
    [JsonPropertyName("type")]
    public object? Type { get; set; }

    /// <summary>[CARIN-BB] Reference to the individual or organization to whom any payment will be made.</summary>
    [JsonPropertyName("party")]
    public object? Party { get; set; }

}

/// <summary>
/// Component class for ExplanationOfBenefit.careTeam
/// </summary>
public sealed class ExplanationOfBenefitPharmacyCareTeamComponent
{
    /// <summary>[HEDIS][CARIN-BB] A number to uniquely identify care team entries.</summary>
    [JsonPropertyName("sequence")]
    public object? Sequence { get; set; }

    /// <summary>[HEDIS][CARIN-BB] Member of the team who provided the product or service.</summary>
    [JsonPropertyName("provider")]
    public ResourceReference? Provider { get; set; }

    /// <summary>[CARIN-BB] The lead, assisting or supervising practitioner and their discipline if a multidisciplinary team.</summary>
    [JsonPropertyName("role")]
    public object? Role { get; set; }

}

/// <summary>
/// Component class for ExplanationOfBenefit.supportingInfo
/// </summary>
public sealed class ExplanationOfBenefitPharmacySupportingInfoComponent
{
    /// <summary>[CARIN-BB] A number to uniquely identify supporting information entries.</summary>
    [JsonPropertyName("sequence")]
    public object? Sequence { get; set; }

    /// <summary>[CARIN-BB] The general class of the information supplied: information; exception; accident, employment; onset, etc.</summary>
    [JsonPropertyName("category")]
    public object? Category { get; set; }

    /// <summary>[CARIN-BB] Additional data or information such as resources, documents, images etc. including references to the data or the actual inclusion of the data.</summary>
    [JsonPropertyName("value")]
    public object? Value { get; set; }

    /// <summary>[CARIN-BB] System and code pertaining to the specific information regarding special conditions relating to the setting, treatment or patient  for which care is sought.</summary>
    [JsonPropertyName("code")]
    public object? Code { get; set; }

    /// <summary>[CARIN-BB] The date when or period to which this information refers.</summary>
    [JsonPropertyName("timing")]
    public object? Timing { get; set; }

}

/// <summary>
/// Component class for ExplanationOfBenefit.insurance
/// </summary>
public sealed class ExplanationOfBenefitPharmacyInsuranceComponent
{
    /// <summary>[CARIN-BB] A flag to indicate that this Coverage is to be used for adjudication of this claim when set to true.</summary>
    [JsonPropertyName("focal")]
    public object? Focal { get; set; }

    /// <summary>[CARIN-BB] Reference to the insurance card level information contained in the Coverage resource. The coverage issuing insurer will use these details to locate the patient's actual coverage within the insurer's information system.</summary>
    [JsonPropertyName("coverage")]
    public object? Coverage { get; set; }

}

/// <summary>
/// Component class for ExplanationOfBenefit.item
/// </summary>
public sealed class ExplanationOfBenefitPharmacyItemComponent
{
    /// <summary>[CARIN-BB] A number to uniquely identify item entries.</summary>
    [JsonPropertyName("sequence")]
    public object? Sequence { get; set; }

    /// <summary>[HEDIS] The type of revenue or cost center providing the product and/or service.</summary>
    [JsonPropertyName("revenue")]
    public object? Revenue { get; set; }

    /// <summary>[CARIN-BB] When the value is a group code then this item collects a set of related claim details, otherwise this contains the product, service, drug or other billing code for the item.</summary>
    [JsonPropertyName("productOrService")]
    public object? ProductOrService { get; set; }

    /// <summary>[HEDIS] Item typification or modifiers codes to convey additional context for the product or service.</summary>
    [JsonPropertyName("modifier")]
    public object? Modifier { get; set; }

    /// <summary>[HEDIS][CARIN-BB] The date or dates when the service or product was supplied, performed or completed.</summary>
    [JsonPropertyName("serviced")]
    public object? Serviced { get; set; }

    /// <summary>[HEDIS] Where the product or service was provided.</summary>
    [JsonPropertyName("location")]
    public CodeableConcept? Location { get; set; }

    /// <summary>[CARIN-BB] The number of repetitions of a service or product.</summary>
    [JsonPropertyName("quantity")]
    public object? Quantity { get; set; }

    /// <summary>[CARIN-BB] The numbers associated with notes below which apply to the adjudication of this item.</summary>
    [JsonPropertyName("noteNumber")]
    public object? NoteNumber { get; set; }

    /// <summary>[CARIN-BB] If this item is a group then the values here are a summary of the adjudication of the detail items. If this item is a simple product or service then this is the result of the adjudication of this item.</summary>
    [JsonPropertyName("adjudication")]
    public object? Adjudication { get; set; }

    /// <summary>[CARIN-BB] Second-tier of goods and services.</summary>
    [JsonPropertyName("detail")]
    public object? Detail { get; set; }

}

/// <summary>
/// Component class for ExplanationOfBenefit.payment
/// </summary>
public sealed class ExplanationOfBenefitPharmacyPaymentComponent
{
    /// <summary>[CARIN-BB] Whether this represents partial or complete payment of the benefits payable.</summary>
    [JsonPropertyName("type")]
    public object? Type { get; set; }

    /// <summary>[CARIN-BB] Estimated date the payment will be issued or the actual issue date of payment.</summary>
    [JsonPropertyName("date")]
    public object? Date { get; set; }

}

/// <summary>
/// Component class for ExplanationOfBenefit.processNote
/// </summary>
public sealed class ExplanationOfBenefitPharmacyProcessNoteComponent
{
    /// <summary>[CARIN-BB] The explanation or description associated with the processing.</summary>
    [JsonPropertyName("text")]
    public object? Text { get; set; }

}
