// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-medicationadministration
// Generated at: 2026-02-23T20:22:48.9007694Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core MedicationAdministration DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-medicationadministration</para>
/// </summary>
public sealed class HEDISCoreMedicationAdministration
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; set; } = "MedicationAdministration";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>[HEDIS] The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; set; }

    /// <summary>[HEDIS] Will generally be set to show that the administration has been completed.  For some long running administrations such as infusions, it is possible for an administration to be started but not completed or it may be paused while some other process is under way.</summary>
    [JsonPropertyName("status")]
    public object? Status { get; set; }

    /// <summary>[HEDIS] Identifies the medication that was administered. This is either a link to a resource representing the details of the medication or a simple attribute carrying a code that identifies the medication from a known list of medications.</summary>
    [JsonPropertyName("medication")]
    public CodeableConcept? Medication { get; set; }

    /// <summary>[HEDIS] The person or animal or group receiving the medication.</summary>
    [JsonPropertyName("subject")]
    public ResourceReference? Subject { get; set; }

    /// <summary>[HEDIS] A specific date/time or interval of time during which the administration took place (or did not take place, when the 'notGiven' attribute is true). For many administrations, such as swallowing a tablet the use of dateTime is more appropriate.</summary>
    [JsonPropertyName("effective")]
    public object? Effective { get; set; }

}
