// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-encounter
// Generated at: 2026-02-23T20:22:48.8697139Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core Encounter DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-encounter</para>
/// </summary>
public sealed class HEDISCoreEncounter
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; set; } = "Encounter";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>[HEDIS] The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; set; }

    /// <summary>[US Core] Identifier(s) by which this encounter is known.</summary>
    [JsonPropertyName("identifier")]
    public EncounterIdentifierComponent? Identifier { get; set; }

    /// <summary>[US Core] planned | arrived | triaged | in-progress | onleave | finished | cancelled +.</summary>
    [JsonPropertyName("status")]
    public object? Status { get; set; }

    /// <summary>[US Core] Concepts representing classification of patient encounter such as ambulatory (outpatient), inpatient, emergency, home health or others due to local variations.</summary>
    [JsonPropertyName("class")]
    public object? Class { get; set; }

    /// <summary>[US Core] Specific type of encounter (e.g. e-mail consultation, surgical day-care, skilled nursing, rehabilitation).</summary>
    [JsonPropertyName("type")]
    public object? Type { get; set; }

    /// <summary>The patient present at the encounter</summary>
    [JsonPropertyName("subject")]
    public ResourceReference? Subject { get; set; }

    /// <summary>[US Core] The list of people responsible for providing the service.</summary>
    [JsonPropertyName("participant")]
    public EncounterParticipantComponent? Participant { get; set; }

    /// <summary>[HEDIS][US Core] The start and end time of the encounter.</summary>
    [JsonPropertyName("period")]
    public object? Period { get; set; }

    /// <summary>[US Core] Reason the encounter takes place, expressed as a code. For admissions, this can be used for a coded admission diagnosis.</summary>
    [JsonPropertyName("reasonCode")]
    public object? ReasonCode { get; set; }

    /// <summary>[HEDIS] The list of diagnosis relevant to this encounter.</summary>
    [JsonPropertyName("diagnosis")]
    public EncounterDiagnosisComponent? Diagnosis { get; set; }

    /// <summary>[US Core] Details about the admission to a healthcare service.</summary>
    [JsonPropertyName("hospitalization")]
    public EncounterHospitalizationComponent? Hospitalization { get; set; }

    /// <summary>[US Core] List of locations where  the patient has been during this encounter.</summary>
    [JsonPropertyName("location")]
    public EncounterLocationComponent? Location { get; set; }

}

/// <summary>
/// Component class for Encounter.identifier
/// </summary>
public sealed class EncounterIdentifierComponent
{
    /// <summary>[US Core] Establishes the namespace for the value - that is, a URL that describes a set values that are unique.</summary>
    [JsonPropertyName("system")]
    public object? System { get; set; }

    /// <summary>[US Core] The portion of the identifier typically relevant to the user and which is unique within the context of the system.</summary>
    [JsonPropertyName("value")]
    public object? Value { get; set; }

}

/// <summary>
/// Component class for Encounter.participant
/// </summary>
public sealed class EncounterParticipantComponent
{
    /// <summary>[US Core] Role of participant in encounter.</summary>
    [JsonPropertyName("type")]
    public object? Type { get; set; }

    /// <summary>[US Core] The period of time that the specified participant participated in the encounter. These can overlap or be sub-sets of the overall encounter's period.</summary>
    [JsonPropertyName("period")]
    public object? Period { get; set; }

    /// <summary>[HEDIS][US Core] Persons involved in the encounter other than the patient.</summary>
    [JsonPropertyName("individual")]
    public ResourceReference? Individual { get; set; }

}

/// <summary>
/// Component class for Encounter.diagnosis
/// </summary>
public sealed class EncounterDiagnosisComponent
{
    /// <summary>[HEDIS] Reason the encounter takes place, as specified using information from another resource. For admissions, this is the admission diagnosis. The indication will typically be a Condition (with other resources referenced in the evidence.detail), or a Procedure.</summary>
    [JsonPropertyName("condition")]
    public ResourceReference? Condition { get; set; }

}

/// <summary>
/// Component class for Encounter.hospitalization
/// </summary>
public sealed class EncounterHospitalizationComponent
{
    /// <summary>[US Core] Category or kind of location after discharge.</summary>
    [JsonPropertyName("dischargeDisposition")]
    public object? DischargeDisposition { get; set; }

}

/// <summary>
/// Component class for Encounter.location
/// </summary>
public sealed class EncounterLocationComponent
{
    /// <summary>[US Core] The location where the encounter takes place.</summary>
    [JsonPropertyName("location")]
    public object? Location { get; set; }

}
