// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-observation-blood-pressure
// Generated at: 2026-02-23T20:22:48.9071966Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core Observation DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-observation-blood-pressure</para>
/// </summary>
public sealed record HEDISCoreObservationBloodPressure
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; init; } = "Observation";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>[US Core] The status of the result value.</summary>
    [JsonPropertyName("status")]
    public object? Status { get; init; }

    /// <summary>[US Core] A code that classifies the general type of observation being made.</summary>
    [JsonPropertyName("category")]
    public object? Category { get; init; }

    /// <summary>[US Core] Describes what was observed. Sometimes this is called the observation "name".</summary>
    [JsonPropertyName("code")]
    public ObservationBloodPressureCodeComponent? Code { get; init; }

    /// <summary>[HEDIS] The patient, or group of patients, location, or device this observation is about and into whose record the observation is placed. If the actual focus of the observation is different from the subject (or a sample of, part, or region of the subject), the `focus` element or the `code` itself specifies the actual focus of the observation.</summary>
    [JsonPropertyName("subject")]
    public object? Subject { get; init; }

    /// <summary>Often just a dateTime for Vital Signs</summary>
    [JsonPropertyName("effective")]
    public object? Effective { get; init; }

    /// <summary>[HEDIS] The information determined as a result of making the observation, if the information has a simple value.</summary>
    [JsonPropertyName("value")]
    public object? Value { get; init; }

    /// <summary>[US Core] Provides a reason why the expected value in the element Observation.value[x] is missing.</summary>
    [JsonPropertyName("dataAbsentReason")]
    public object? DataAbsentReason { get; init; }

    /// <summary>[US Core] Some observations have multiple component observations.  These component observations are expressed as separate code value pairs that share the same attributes.  Examples include systolic and diastolic component observations for blood pressure measurement and multiple component observations for genetics observations.</summary>
    [JsonPropertyName("component")]
    public ObservationBloodPressureComponentComponent? Component { get; init; }

}

/// <summary>
/// Component class for Observation.code
/// </summary>
public sealed record ObservationBloodPressureCodeComponent
{
    [JsonPropertyName("coding")]
    public object? Coding { get; init; }

}

/// <summary>
/// Component class for Observation.component
/// </summary>
public sealed record ObservationBloodPressureComponentComponent
{
    [JsonPropertyName("code")]
    public object? Code { get; init; }

    /// <summary>[US Core] The information determined as a result of making the observation, if the information has a simple value.</summary>
    [JsonPropertyName("value")]
    public Quantity? Value { get; init; }

}
