// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-observation
// Generated at: 2026-02-23T20:22:48.9152766Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core Observation DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-observation</para>
/// </summary>
public sealed class HEDISCoreObservation
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; set; } = "Observation";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("meta")]
    public object? Meta { get; set; }

    [JsonPropertyName("status")]
    public object? Status { get; set; }

    /// <summary>[HEDIS][US Core] A code that classifies the general type of observation being made.</summary>
    [JsonPropertyName("category")]
    public object? Category { get; set; }

    [JsonPropertyName("code")]
    public object? Code { get; set; }

    /// <summary>[HEDIS][US Core] The patient, or group of patients, location, or device this observation is about and into whose record the observation is placed. If the actual focus of the observation is different from the subject (or a sample of, part, or region of the subject), the `focus` element or the `code` itself specifies the actual focus of the observation.</summary>
    [JsonPropertyName("subject")]
    public object? Subject { get; set; }

    [JsonPropertyName("effective")]
    public object? Effective { get; set; }

    [JsonPropertyName("value")]
    public object? Value { get; set; }

}
