// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-questionnaireresponse
// Generated at: 2026-02-23T20:22:48.9273807Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core QuestionnaireResponse DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-questionnaireresponse</para>
/// </summary>
public sealed record HEDISCoreQuestionnaireResponse
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; init; } = "QuestionnaireResponse";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>[HEDIS] The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; init; }

    /// <summary>[US Core] A business identifier assigned to a particular completed (or partially completed) questionnaire.</summary>
    [JsonPropertyName("identifier")]
    public object? Identifier { get; init; }

    /// <summary>[US Core] The Questionnaire that defines and organizes the questions for which answers are being provided.</summary>
    [JsonPropertyName("questionnaire")]
    public string? Questionnaire { get; init; }

    /// <summary>[US Core] The position of the questionnaire response within its overall lifecycle.</summary>
    [JsonPropertyName("status")]
    public object? Status { get; init; }

    /// <summary>[HEDIS][US Core] The subject of the questionnaire response.  This could be a patient, organization, practitioner, device, etc.  This is who/what the answers apply to, but is not necessarily the source of information.</summary>
    [JsonPropertyName("subject")]
    public ResourceReference? Subject { get; init; }

    /// <summary>[US Core] The date and/or time that this set of answers were last changed.</summary>
    [JsonPropertyName("authored")]
    public object? Authored { get; init; }

    /// <summary>[HEDIS][US Core] Person who received the answers to the questions in the QuestionnaireResponse and recorded them in the system.</summary>
    [JsonPropertyName("author")]
    public ResourceReference? Author { get; init; }

    /// <summary>[US Core] A group or question item from the original questionnaire for which answers are provided.</summary>
    [JsonPropertyName("item")]
    public QuestionnaireResponseItemComponent? Item { get; init; }

}

/// <summary>
/// Component class for QuestionnaireResponse.meta
/// </summary>
public sealed record QuestionnaireResponseMetaComponent
{
    /// <summary>[US Core] Tags applied to this resource. Tags are intended to be used to identify and relate resources to process and workflow, and applications are not required to consider the tags when interpreting the meaning of a resource.</summary>
    [JsonPropertyName("tag")]
    public object? Tag { get; init; }

}

/// <summary>
/// Component class for QuestionnaireResponse.questionnaire
/// </summary>
public sealed record QuestionnaireResponseQuestionnaireComponent
{
    /// <summary>[US Core] The title or other name to display when referencing a resource by canonical URL.</summary>
    [JsonPropertyName("extension")]
    public Extension? Extension { get; init; }

}

/// <summary>
/// Component class for QuestionnaireResponse.item
/// </summary>
public sealed record QuestionnaireResponseItemComponent
{
    /// <summary>[US Core] Media to render/make available as an accompaniment to the question being asked</summary>
    [JsonPropertyName("extension")]
    public Extension? Extension { get; init; }

    /// <summary>[US Core] The item from the Questionnaire that corresponds to this item in the QuestionnaireResponse resource.</summary>
    [JsonPropertyName("linkId")]
    public object? LinkId { get; init; }

    /// <summary>[US Core] Text that is displayed above the contents of the group or as the text of the question being answered.</summary>
    [JsonPropertyName("text")]
    public object? Text { get; init; }

    /// <summary>[US Core] The respondent's answer(s) to the question.</summary>
    [JsonPropertyName("answer")]
    public object? Answer { get; init; }

    /// <summary>[US Core] Questions or sub-groups nested beneath a question or group.</summary>
    [JsonPropertyName("item")]
    public object? Item { get; init; }

}
