// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-medicationdispense
// Generated at: 2026-02-23T20:22:48.9028409Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core MedicationDispense DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-medicationdispense</para>
/// </summary>
public sealed record HEDISCoreMedicationDispense
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; init; } = "MedicationDispense";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>[HEDIS] The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; init; }

    /// <summary>[HEDIS] A code specifying the state of the set of dispense events.</summary>
    [JsonPropertyName("status")]
    public object? Status { get; init; }

    /// <summary>[HEDIS] Identifies the medication being administered. This is either a link to a resource representing the details of the medication or a simple attribute carrying a code that identifies the medication from a known list of medications.</summary>
    [JsonPropertyName("medication")]
    public CodeableConcept? Medication { get; init; }

    /// <summary>[HEDIS] A link to a resource representing the person or the group to whom the medication will be given.</summary>
    [JsonPropertyName("subject")]
    public ResourceReference? Subject { get; init; }

    [JsonPropertyName("quantity")]
    public object? Quantity { get; init; }

    /// <summary>[HEDIS] The amount of medication expressed as a timing amount.</summary>
    [JsonPropertyName("daysSupply")]
    public object? DaysSupply { get; init; }

    /// <summary>[HEDIS] The time the dispensed product was provided to the patient or their representative.</summary>
    [JsonPropertyName("whenHandedOver")]
    public object? WhenHandedOver { get; init; }

}
