// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-claim-outpatient-institutional
// Generated at: 2026-02-23T20:22:48.8103740Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core Claim DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-claim-outpatient-institutional</para>
/// </summary>
public sealed record HEDISCoreClaimOutpatientInstitutional
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; init; } = "Claim";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>[HEDIS][CARIN-BB] The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; init; }

    /// <summary>[CARIN-BB] The category of claim, e.g. oral, pharmacy, vision, institutional, professional.</summary>
    [JsonPropertyName("type")]
    public ClaimOutpatientInstitutionalTypeComponent? Type { get; init; }

    /// <summary>[CARIN-BB] A finer grained suite of claim type codes which may convey additional information such as Inpatient vs Outpatient and/or a specialty service.</summary>
    [JsonPropertyName("subType")]
    public ClaimOutpatientInstitutionalSubTypeComponent? SubType { get; init; }

    /// <summary>[HEDIS] The party to whom the professional services and/or products have been supplied or are being considered and for whom actual or forecast reimbursement is sought.</summary>
    [JsonPropertyName("patient")]
    public ResourceReference? Patient { get; init; }

    /// <summary>[CARIN-BB] The period for which charges are being submitted.</summary>
    [JsonPropertyName("billablePeriod")]
    public object? BillablePeriod { get; init; }

    /// <summary>[CARIN-BB] The members of the team who provided the products and services.</summary>
    [JsonPropertyName("careTeam")]
    public ClaimOutpatientInstitutionalCareTeamComponent? CareTeam { get; init; }

    [JsonPropertyName("supportingInfo")]
    public ClaimOutpatientInstitutionalSupportingInfoComponent? SupportingInfo { get; init; }

    /// <summary>[HEDIS][CARIN-BB] Information about diagnoses relevant to the claim items.</summary>
    [JsonPropertyName("diagnosis")]
    public ClaimOutpatientInstitutionalDiagnosisComponent? Diagnosis { get; init; }

    /// <summary>[HEDIS] Procedures performed on the patient relevant to the billing items with the claim.</summary>
    [JsonPropertyName("procedure")]
    public ClaimOutpatientInstitutionalProcedureComponent? Procedure { get; init; }

    /// <summary>[HEDIS][CARIN-BB] A claim line. Either a simple  product or service or a 'group' of details which can each be a simple items or groups of sub-details.</summary>
    [JsonPropertyName("item")]
    public ClaimOutpatientInstitutionalItemComponent? Item { get; init; }

}

/// <summary>
/// Component class for Claim.type
/// </summary>
public sealed record ClaimOutpatientInstitutionalTypeComponent
{
    /// <summary>[CARIN-BB] A reference to a code defined by a terminology system.</summary>
    [JsonPropertyName("coding")]
    public object? Coding { get; init; }

}

/// <summary>
/// Component class for Claim.subType
/// </summary>
public sealed record ClaimOutpatientInstitutionalSubTypeComponent
{
    [JsonPropertyName("coding")]
    public object? Coding { get; init; }

}

/// <summary>
/// Component class for Claim.careTeam
/// </summary>
public sealed record ClaimOutpatientInstitutionalCareTeamComponent
{
    /// <summary>[HEDIS] A number to uniquely identify care team entries.</summary>
    [JsonPropertyName("sequence")]
    public object? Sequence { get; init; }

    /// <summary>[HEDIS][CARIN-BB]  Member of the team who provided the product or service.</summary>
    [JsonPropertyName("provider")]
    public ResourceReference? Provider { get; init; }

}

/// <summary>
/// Component class for Claim.supportingInfo
/// </summary>
public sealed record ClaimOutpatientInstitutionalSupportingInfoComponent
{
    [JsonPropertyName("category")]
    public object? Category { get; init; }

    [JsonPropertyName("code")]
    public object? Code { get; init; }

    [JsonPropertyName("value")]
    public object? Value { get; init; }

}

/// <summary>
/// Component class for Claim.diagnosis
/// </summary>
public sealed record ClaimOutpatientInstitutionalDiagnosisComponent
{
    /// <summary>[HEDIS] A number to uniquely identify diagnosis entries.</summary>
    [JsonPropertyName("sequence")]
    public object? Sequence { get; init; }

    /// <summary>[CARIN-BB] The nature of illness or problem in a coded form or as a reference to an external defined Condition.</summary>
    [JsonPropertyName("diagnosis")]
    public CodeableConcept? Diagnosis { get; init; }

    /// <summary>[CARIN-BB] When the condition was observed or the relative ranking.</summary>
    [JsonPropertyName("type")]
    public object? Type { get; init; }

}

/// <summary>
/// Component class for Claim.procedure
/// </summary>
public sealed record ClaimOutpatientInstitutionalProcedureComponent
{
    /// <summary>[HEDIS] A number to uniquely identify procedure entries.</summary>
    [JsonPropertyName("sequence")]
    public object? Sequence { get; init; }

    /// <summary>[HEDIS] The code or reference to a Procedure resource which identifies the clinical intervention performed.</summary>
    [JsonPropertyName("procedure")]
    public CodeableConcept? Procedure { get; init; }

}

/// <summary>
/// Component class for Claim.item
/// </summary>
public sealed record ClaimOutpatientInstitutionalItemComponent
{
    /// <summary>[CARIN-BB] A number to uniquely identify item entries.</summary>
    [JsonPropertyName("sequence")]
    public object? Sequence { get; init; }

    /// <summary>[HEDIS] Diagnosis applicable for this service or product.</summary>
    [JsonPropertyName("diagnosisSequence")]
    public object? DiagnosisSequence { get; init; }

    /// <summary>[HEDIS] Procedures applicable for this service or product.</summary>
    [JsonPropertyName("procedureSequence")]
    public object? ProcedureSequence { get; init; }

    /// <summary>[HEDIS] Exceptions, special conditions and supporting information applicable for this service or product.</summary>
    [JsonPropertyName("informationSequence")]
    public object? InformationSequence { get; init; }

    [JsonPropertyName("revenue")]
    public object? Revenue { get; init; }

    /// <summary>[CARIN-BB] When the value is a group code then this item collects a set of related claim details, otherwise this contains the product, service, drug or other billing code for the item.</summary>
    [JsonPropertyName("productOrService")]
    public object? ProductOrService { get; init; }

    /// <summary>[CARIN-BB] Item typification or modifiers codes to convey additional context for the product or service.</summary>
    [JsonPropertyName("modifier")]
    public object? Modifier { get; init; }

    /// <summary>[HEDIS] The date or dates when the service or product was supplied, performed or completed.</summary>
    [JsonPropertyName("serviced")]
    public object? Serviced { get; init; }

    /// <summary>[CARIN-BB] The number of repetitions of a service or product.</summary>
    [JsonPropertyName("quantity")]
    public object? Quantity { get; init; }

}
