// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-meta
// Generated at: 2026-02-23T20:22:48.9047366Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core Meta DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-meta</para>
/// </summary>
public sealed class HEDISCoreMeta
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; set; } = "Meta";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("tag")]
    public object? Tag { get; set; }

}
