// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-observation-bmi
// Generated at: 2026-02-23T20:22:48.9104938Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core Observation DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-observation-bmi</para>
/// </summary>
public sealed record HEDISCoreObservationBMI
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; init; } = "Observation";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    [JsonPropertyName("status")]
    public object? Status { get; init; }

    /// <summary>[US Core] Describes what was observed. Sometimes this is called the observation "name".</summary>
    [JsonPropertyName("code")]
    public ObservationBMICodeComponent? Code { get; init; }

    [JsonPropertyName("effective")]
    public object? Effective { get; init; }

    [JsonPropertyName("value")]
    public Quantity? Value { get; init; }

}

/// <summary>
/// Component class for Observation.code
/// </summary>
public sealed record ObservationBMICodeComponent
{
    [JsonPropertyName("coding")]
    public object? Coding { get; init; }

}
