// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-relatedperson
// Generated at: 2026-02-23T20:22:48.9302977Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core RelatedPerson DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-relatedperson</para>
/// </summary>
public sealed class HEDISCoreRelatedPerson
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; set; } = "RelatedPerson";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>[HEDIS] The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; set; }

    /// <summary>[US Core] Whether this related person record is in active use.</summary>
    [JsonPropertyName("active")]
    public object? Active { get; set; }

    /// <summary>[HEDIS] The patient this person is related to.</summary>
    [JsonPropertyName("patient")]
    public ResourceReference? Patient { get; set; }

    /// <summary>[US Core] The nature of the relationship between a patient and the related person.</summary>
    [JsonPropertyName("relationship")]
    public object? Relationship { get; set; }

    /// <summary>[US Core]  A name associated with the person.</summary>
    [JsonPropertyName("name")]
    public object? Name { get; set; }

    /// <summary>[US Core] A contact detail for the person, e.g. a telephone number or an email address.</summary>
    [JsonPropertyName("telecom")]
    public object? Telecom { get; set; }

    /// <summary>[US Core] Address where the related person can be contacted or visited.</summary>
    [JsonPropertyName("address")]
    public object? Address { get; set; }

}
