// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-organization
// Generated at: 2026-02-23T20:22:48.9172643Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core Organization DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-organization</para>
/// </summary>
public sealed class HEDISCoreOrganization
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; set; } = "Organization";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>[HEDIS][CARIN-BB] The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; set; }

    /// <summary>[CARIN-BB] Identifier for the organization that is used to identify the organization across multiple disparate systems.</summary>
    [JsonPropertyName("identifier")]
    public object? Identifier { get; set; }

}

/// <summary>
/// Component class for Organization.meta
/// </summary>
public sealed class OrganizationMetaComponent
{
    /// <summary>[CARIN-BB] When the resource last changed - e.g. when the version changed.</summary>
    [JsonPropertyName("lastUpdated")]
    public object? LastUpdated { get; set; }

    [JsonPropertyName("profile")]
    public object? Profile { get; set; }

}
