// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-procedure
// Generated at: 2026-02-23T20:22:48.9257099Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core Procedure DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-procedure</para>
/// </summary>
public sealed record HEDISCoreProcedure
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; init; } = "Procedure";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>[HEDIS] The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; init; }

    /// <summary>[US Core] A code specifying the state of the procedure. Generally, this will be the in-progress or completed state.</summary>
    [JsonPropertyName("status")]
    public object? Status { get; init; }

    [JsonPropertyName("category")]
    public object? Category { get; init; }

    /// <summary>[US Core] The specific procedure that is performed. Use text if the exact nature of the procedure cannot be coded (e.g. "Laparoscopic Appendectomy").</summary>
    [JsonPropertyName("code")]
    public object? Code { get; init; }

    /// <summary>[HEDIS][US Core] The person, animal or group on which the procedure was performed.</summary>
    [JsonPropertyName("subject")]
    public ResourceReference? Subject { get; init; }

    /// <summary>[US Core] Estimated or actual date, date-time, period, or age when the procedure was performed.  Allows a period to support complex procedures that span more than one date, and also allows for the length of the procedure to be captured.</summary>
    [JsonPropertyName("performed")]
    public object? Performed { get; init; }

    /// <summary>[HEDIS] Detailed and structured anatomical location information. Multiple locations are allowed - e.g. multiple punch biopsies of a lesion.</summary>
    [JsonPropertyName("bodySite")]
    public object? BodySite { get; init; }

}
