// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-immunization
// Generated at: 2026-02-23T20:22:48.8933078Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core Immunization DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-immunization</para>
/// </summary>
public sealed class HEDISCoreImmunization
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; set; } = "Immunization";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>[HEDIS] The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; set; }

    /// <summary>[US Core] Indicates the current status of the immunization event.</summary>
    [JsonPropertyName("status")]
    public object? Status { get; set; }

    /// <summary>[US Core] Indicates the reason the immunization event was not performed.</summary>
    [JsonPropertyName("statusReason")]
    public object? StatusReason { get; set; }

    /// <summary>[US Core] Vaccine that was administered or was to be administered.</summary>
    [JsonPropertyName("vaccineCode")]
    public object? VaccineCode { get; set; }

    /// <summary>[HEDIS] [US Core] The patient who either received or did not receive the immunization.</summary>
    [JsonPropertyName("patient")]
    public ResourceReference? Patient { get; set; }

    /// <summary>[HEDIS][US Core] Date vaccine administered or was to be administered.</summary>
    [JsonPropertyName("occurrence")]
    public string? Occurrence { get; set; }

    /// <summary>[US Core] An indication that the content of the record is based on information from the person who administered the vaccine. This reflects the context under which the data was originally recorded.</summary>
    [JsonPropertyName("primarySource")]
    public object? PrimarySource { get; set; }

}
