// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-claim-pharmacy
// Generated at: 2026-02-23T20:22:48.8462817Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core Claim DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-claim-pharmacy</para>
/// </summary>
public sealed record HEDISCoreClaimPharmacy
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; init; } = "Claim";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>[HEDIS][CARIN-BB] The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; init; }

    /// <summary>[CARIN-BB] The category of claim, e.g. oral, pharmacy, vision, institutional, professional.</summary>
    [JsonPropertyName("type")]
    public ClaimPharmacyTypeComponent? Type { get; init; }

    /// <summary>[HEDIS] The party to whom the professional services and/or products have been supplied or are being considered and for whom actual or forecast reimbursement is sought.</summary>
    [JsonPropertyName("patient")]
    public ResourceReference? Patient { get; init; }

    [JsonPropertyName("careTeam")]
    public ClaimPharmacyCareTeamComponent? CareTeam { get; init; }

    /// <summary>[HEDIS][CARIN-BB] Additional information codes regarding exceptions, special considerations, the condition, situation, prior or concurrent issues.</summary>
    [JsonPropertyName("supportingInfo")]
    public ClaimPharmacySupportingInfoComponent? SupportingInfo { get; init; }

    /// <summary>[HEDIS][CARIN-BB] A claim line. Either a simple  product or service or a 'group' of details which can each be a simple items or groups of sub-details.</summary>
    [JsonPropertyName("item")]
    public ClaimPharmacyItemComponent? Item { get; init; }

}

/// <summary>
/// Component class for Claim.type
/// </summary>
public sealed record ClaimPharmacyTypeComponent
{
    [JsonPropertyName("coding")]
    public object? Coding { get; init; }

}

/// <summary>
/// Component class for Claim.careTeam
/// </summary>
public sealed record ClaimPharmacyCareTeamComponent
{
    /// <summary>[HEDIS] A number to uniquely identify care team entries.</summary>
    [JsonPropertyName("sequence")]
    public object? Sequence { get; init; }

    /// <summary>[HEDIS][CARIN-BB] Member of the team who provided the product or service.</summary>
    [JsonPropertyName("provider")]
    public ResourceReference? Provider { get; init; }

}

/// <summary>
/// Component class for Claim.supportingInfo
/// </summary>
public sealed record ClaimPharmacySupportingInfoComponent
{
    /// <summary>[CARIN-BB] The general class of the information supplied: information; exception; accident, employment; onset, etc.</summary>
    [JsonPropertyName("category")]
    public object? Category { get; init; }

    [JsonPropertyName("value")]
    public Quantity? Value { get; init; }

}

/// <summary>
/// Component class for Claim.item
/// </summary>
public sealed record ClaimPharmacyItemComponent
{
    /// <summary>[CARIN-BB] A number to uniquely identify item entries.</summary>
    [JsonPropertyName("sequence")]
    public object? Sequence { get; init; }

    /// <summary>[HEDIS] Diagnosis applicable for this service or product.</summary>
    [JsonPropertyName("diagnosisSequence")]
    public object? DiagnosisSequence { get; init; }

    /// <summary>[HEDIS] Procedures applicable for this service or product.</summary>
    [JsonPropertyName("procedureSequence")]
    public object? ProcedureSequence { get; init; }

    /// <summary>[HEDIS] The type of revenue or cost center providing the product and/or service.</summary>
    [JsonPropertyName("revenue")]
    public object? Revenue { get; init; }

    /// <summary>[CARIN-BB] When the value is a group code then this item collects a set of related claim details, otherwise this contains the product, service, drug or other billing code for the item.</summary>
    [JsonPropertyName("productOrService")]
    public object? ProductOrService { get; init; }

    /// <summary>[HEDIS] Item typification or modifiers codes to convey additional context for the product or service.</summary>
    [JsonPropertyName("modifier")]
    public object? Modifier { get; init; }

    /// <summary>[HEDIS] The date or dates when the service or product was supplied, performed or completed.</summary>
    [JsonPropertyName("serviced")]
    public object? Serviced { get; init; }

    /// <summary>[HEDIS] Where the product or service was provided.</summary>
    [JsonPropertyName("location")]
    public CodeableConcept? Location { get; init; }

    /// <summary>[CARIN-BB] The number of repetitions of a service or product.</summary>
    [JsonPropertyName("quantity")]
    public object? Quantity { get; init; }

}
