// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-claimresponse
// Generated at: 2026-02-23T20:22:48.8558323Z
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// HEDIS Core ClaimResponse DTO.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-claimresponse</para>
/// </summary>
public sealed class HEDISCoreClaimResponse
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; set; } = "ClaimResponse";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>[HEDIS] The metadata about a resource. This is content in the resource that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; set; }

    /// <summary>[HEDIS] A finer grained suite of claim type codes which may convey additional information such as Inpatient vs Outpatient and/or a specialty service.</summary>
    [JsonPropertyName("type")]
    public object? Type { get; set; }

    /// <summary>[HEDIS] The party to whom the professional services and/or products have been supplied or are being considered and for whom actual for facast reimbursement is sought.</summary>
    [JsonPropertyName("patient")]
    public ResourceReference? Patient { get; set; }

    /// <summary>[HEDIS] Original request resource reference.</summary>
    [JsonPropertyName("request")]
    public object? Request { get; set; }

    /// <summary>[HEDIS] The first-tier service adjudications for payor added product or service lines.</summary>
    [JsonPropertyName("addItem")]
    public ClaimResponseAddItemComponent? AddItem { get; set; }

}

/// <summary>
/// Component class for ClaimResponse.item
/// </summary>
public sealed class ClaimResponseItemComponent
{
    [JsonPropertyName("itemSequence")]
    public object? ItemSequence { get; set; }

}

/// <summary>
/// Component class for ClaimResponse.addItem
/// </summary>
public sealed class ClaimResponseAddItemComponent
{
    [JsonPropertyName("serviced")]
    public object? Serviced { get; set; }

}
