// <auto-generated>
// Generated from HEDIS Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-patient
// This DTO matches Hl7.Fhir.Model.Patient naming for drop-in replacement.
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Ncqa.Hedis.Core._2025;

/// <summary>
/// Information about an individual or animal receiving health care services.
/// <para>Profile: https://ncqa.org/fhir/StructureDefinition/hedis-core-patient</para>
/// </summary>
public sealed class Patient
{
    /// <summary>The FHIR resource type.</summary>
    [JsonPropertyName("resourceType")]
    public string ResourceType { get; set; } = "Patient";

    /// <summary>Logical id of this artifact.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>The metadata about a resource.</summary>
    [JsonPropertyName("meta")]
    public Meta? Meta { get; set; }

    /// <summary>A set of rules under which this content was created.</summary>
    [JsonPropertyName("implicitRules")]
    public string? ImplicitRules { get; set; }

    /// <summary>Language of the resource content.</summary>
    [JsonPropertyName("language")]
    public string? Language { get; set; }

    /// <summary>Text summary of the resource.</summary>
    [JsonPropertyName("text")]
    public Narrative? Text { get; set; }

    /// <summary>Additional content defined by implementations.</summary>
    [JsonPropertyName("extension")]
    public List<Extension>? Extension { get; set; }

    /// <summary>Extensions that cannot be ignored.</summary>
    [JsonPropertyName("modifierExtension")]
    public List<Extension>? ModifierExtension { get; set; }

    /// <summary>An identifier for this patient.</summary>
    [JsonPropertyName("identifier")]
    public List<Identifier>? Identifier { get; set; }

    /// <summary>Whether this patient's record is in active use.</summary>
    [JsonPropertyName("active")]
    public bool? Active { get; set; }

    /// <summary>A name associated with the patient.</summary>
    [JsonPropertyName("name")]
    public List<HumanName>? Name { get; set; }

    /// <summary>A contact detail for the individual.</summary>
    [JsonPropertyName("telecom")]
    public List<ContactPoint>? Telecom { get; set; }

    /// <summary>male | female | other | unknown.</summary>
    [JsonPropertyName("gender")]
    public string? Gender { get; set; }

    /// <summary>The date of birth for the individual.</summary>
    [JsonPropertyName("birthDate")]
    public string? BirthDate { get; set; }

    /// <summary>Indicates if the individual is deceased (boolean).</summary>
    [JsonPropertyName("deceasedBoolean")]
    public bool? DeceasedBoolean { get; set; }

    /// <summary>Indicates if the individual is deceased (dateTime).</summary>
    [JsonPropertyName("deceasedDateTime")]
    public string? DeceasedDateTime { get; set; }

    /// <summary>An address for the individual.</summary>
    [JsonPropertyName("address")]
    public List<Address>? Address { get; set; }

    /// <summary>Marital (civil) status of a patient.</summary>
    [JsonPropertyName("maritalStatus")]
    public CodeableConcept? MaritalStatus { get; set; }

    /// <summary>Whether patient is part of a multiple birth (boolean).</summary>
    [JsonPropertyName("multipleBirthBoolean")]
    public bool? MultipleBirthBoolean { get; set; }

    /// <summary>Whether patient is part of a multiple birth (order).</summary>
    [JsonPropertyName("multipleBirthInteger")]
    public int? MultipleBirthInteger { get; set; }

    /// <summary>Image of the patient.</summary>
    [JsonPropertyName("photo")]
    public List<Attachment>? Photo { get; set; }

    /// <summary>A contact party (e.g. guardian, partner, friend) for the patient.</summary>
    [JsonPropertyName("contact")]
    public List<ContactComponent>? Contact { get; set; }

    /// <summary>A language which may be used to communicate with the patient.</summary>
    [JsonPropertyName("communication")]
    public List<CommunicationComponent>? Communication { get; set; }

    /// <summary>Patient's nominated primary care provider.</summary>
    [JsonPropertyName("generalPractitioner")]
    public List<ResourceReference>? GeneralPractitioner { get; set; }

    /// <summary>Organization that is the custodian of the patient record.</summary>
    [JsonPropertyName("managingOrganization")]
    public ResourceReference? ManagingOrganization { get; set; }

    /// <summary>Link to another patient resource that concerns the same actual person.</summary>
    [JsonPropertyName("link")]
    public List<LinkComponent>? Link { get; set; }

    /// <summary>
    /// A contact party (e.g. guardian, partner, friend) for the patient.
    /// </summary>
    public sealed class ContactComponent
    {
        /// <summary>The kind of relationship.</summary>
        [JsonPropertyName("relationship")]
        public List<CodeableConcept>? Relationship { get; set; }

        /// <summary>A name associated with the contact person.</summary>
        [JsonPropertyName("name")]
        public HumanName? Name { get; set; }

        /// <summary>A contact detail for the person.</summary>
        [JsonPropertyName("telecom")]
        public List<ContactPoint>? Telecom { get; set; }

        /// <summary>Address for the contact person.</summary>
        [JsonPropertyName("address")]
        public Address? Address { get; set; }

        /// <summary>male | female | other | unknown.</summary>
        [JsonPropertyName("gender")]
        public string? Gender { get; set; }

        /// <summary>Organization that is associated with the contact.</summary>
        [JsonPropertyName("organization")]
        public ResourceReference? Organization { get; set; }

        /// <summary>The period during which this contact person is valid.</summary>
        [JsonPropertyName("period")]
        public Period? Period { get; set; }
    }

    /// <summary>
    /// A language which may be used to communicate with the patient about his or her health.
    /// </summary>
    public sealed class CommunicationComponent
    {
        /// <summary>The language which can be used to communicate with the patient.</summary>
        [JsonPropertyName("language")]
        public CodeableConcept? Language { get; set; }

        /// <summary>Language preference indicator.</summary>
        [JsonPropertyName("preferred")]
        public bool? Preferred { get; set; }
    }

    /// <summary>
    /// Link to another patient resource that concerns the same actual patient.
    /// </summary>
    public sealed class LinkComponent
    {
        /// <summary>The other patient resource that the link refers to.</summary>
        [JsonPropertyName("other")]
        public ResourceReference? Other { get; set; }

        /// <summary>replaced-by | replaces | refer | seealso.</summary>
        [JsonPropertyName("type")]
        public string? Type { get; set; }
    }
}
