using System.Text;
using Hl7.Fhir.Model;
using Hl7.Fhir.Serialization;

namespace ProfileCodeGenerator;

/// <summary>
/// Generates lightweight C# DTOs from FHIR StructureDefinition profiles.
/// The generated code uses System.Text.Json for fast, allocation-efficient deserialization.
/// </summary>
public class FhirProfileCodeGenerator
{
    private readonly GeneratorOptions _options;

    public FhirProfileCodeGenerator(GeneratorOptions? options = null)
    {
        _options = options ?? new GeneratorOptions();
    }

    /// <summary>
    /// Generate C# code from a StructureDefinition profile.
    /// </summary>
    public string Generate(StructureDefinition profile)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Generated from FHIR Profile: {profile.Url}");
        sb.AppendLine($"// Profile Name: {profile.Name}");
        sb.AppendLine($"// Generated at: {DateTime.UtcNow:O}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {_options.Namespace};");
        sb.AppendLine();

        // Get elements to generate
        var elements = GetElementsToGenerate(profile);

        // Group elements by their parent path to identify nested types
        var rootElements = elements.Where(e => GetDepth(e.Path) == 1).ToList();
        var nestedTypes = new Dictionary<string, List<ElementDefinition>>();

        foreach (var element in elements.Where(e => GetDepth(e.Path) > 1))
        {
            var parentPath = GetParentPath(element.Path);
            if (!nestedTypes.ContainsKey(parentPath))
                nestedTypes[parentPath] = new List<ElementDefinition>();
            nestedTypes[parentPath].Add(element);
        }

        // Generate the main class
        var className = _options.ClassNameOverride ?? ToPascalCase(profile.Name ?? profile.Type);
        GenerateClass(sb, className, profile.Type, rootElements, nestedTypes, 0);

        return sb.ToString();
    }

    private void GenerateClass(
        StringBuilder sb,
        string className,
        string fhirType,
        List<ElementDefinition> properties,
        Dictionary<string, List<ElementDefinition>> nestedTypes,
        int indentLevel)
    {
        var indent = new string(' ', indentLevel * 4);

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Lightweight DTO for FHIR {fhirType}");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}public sealed class {className}");
        sb.AppendLine($"{indent}{{");

        foreach (var element in properties)
        {
            var propName = GetPropertyName(element.Path);
            var jsonName = GetJsonName(element.Path);
            var (csharpType, needsNestedClass) = MapToCSharpType(element, nestedTypes);

            // Skip the root element (e.g., "Patient")
            if (GetDepth(element.Path) == 0)
                continue;

            var innerIndent = indent + "    ";

            // Add summary comment
            if (!string.IsNullOrEmpty(element.Short))
            {
                sb.AppendLine($"{innerIndent}/// <summary>");
                sb.AppendLine($"{innerIndent}/// {EscapeXml(element.Short)}");
                sb.AppendLine($"{innerIndent}/// </summary>");
            }

            // Add JsonPropertyName attribute
            sb.AppendLine($"{innerIndent}[JsonPropertyName(\"{jsonName}\")]");

            // Handle cardinality
            var isCollection = element.Max != "1" && element.Max != "0";
            var isRequired = element.Min > 0;

            string finalType;
            if (isCollection)
            {
                finalType = $"List<{csharpType}>?";
            }
            else if (IsValueType(csharpType) && !isRequired)
            {
                finalType = $"{csharpType}?";
            }
            else if (!isRequired)
            {
                finalType = $"{csharpType}?";
            }
            else
            {
                finalType = csharpType;
            }

            sb.AppendLine($"{innerIndent}public {finalType} {propName} {{ get; set; }}");
            sb.AppendLine();
        }

        // Generate nested classes for backbone elements
        foreach (var element in properties)
        {
            var fullPath = element.Path;
            if (nestedTypes.TryGetValue(fullPath, out var nestedElements) && nestedElements.Any())
            {
                var nestedClassName = GetPropertyName(fullPath) + "Component";
                GenerateClass(sb, nestedClassName, fullPath, nestedElements, nestedTypes, indentLevel + 1);
            }
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private List<ElementDefinition> GetElementsToGenerate(StructureDefinition profile)
    {
        // Prefer snapshot, fall back to differential
        var elements = profile.Snapshot?.Element ?? profile.Differential?.Element;

        if (elements == null || !elements.Any())
            return new List<ElementDefinition>();

        // Filter based on options
        return elements.Where(ShouldIncludeElement).ToList();
    }

    private bool ShouldIncludeElement(ElementDefinition element)
    {
        // Always skip the root element definition
        if (!element.Path.Contains('.'))
            return false;

        // Skip extensions unless explicitly included
        if (element.Path.EndsWith(".extension") || element.Path.EndsWith(".modifierExtension"))
            return _options.IncludeExtensions;

        // Skip metadata fields unless explicitly included
        if (element.Path.EndsWith(".meta") || element.Path.EndsWith(".implicitRules") ||
            element.Path.EndsWith(".language") || element.Path.EndsWith(".text") ||
            element.Path.EndsWith(".contained"))
            return _options.IncludeMetadata;

        // Include if MustSupport is true
        if (_options.MustSupportOnly && element.MustSupport != true)
            return false;

        // Include if it has constraints (min > 0, fixed value, pattern, etc.)
        if (_options.ConstrainedOnly)
        {
            var hasConstraints = element.Min > 0 ||
                                element.Fixed != null ||
                                element.Pattern != null ||
                                element.MustSupport == true ||
                                (element.Max != "*" && element.Max != "1");
            if (!hasConstraints)
                return false;
        }

        return true;
    }

    private (string CSharpType, bool NeedsNestedClass) MapToCSharpType(
        ElementDefinition element,
        Dictionary<string, List<ElementDefinition>> nestedTypes)
    {
        var types = element.Type;

        // If no type specified, check if it's a backbone element (has children)
        if (types == null || !types.Any())
        {
            if (nestedTypes.ContainsKey(element.Path))
            {
                return (GetPropertyName(element.Path) + "Component", true);
            }
            return ("object", false);
        }

        // Handle choice types (e.g., value[x])
        if (types.Count > 1)
        {
            // For choice types, use object or a common base
            return ("object", false);
        }

        var fhirType = types.First().Code;
        return (MapFhirTypeToCSharp(fhirType), false);
    }

    private string MapFhirTypeToCSharp(string fhirType)
    {
        return fhirType switch
        {
            // Primitive types
            "boolean" => "bool",
            "integer" => "int",
            "integer64" => "long",
            "string" => "string",
            "decimal" => "decimal",
            "uri" => "string",
            "url" => "string",
            "canonical" => "string",
            "base64Binary" => "string",
            "instant" => "DateTimeOffset",
            "date" => "string",  // Keep as string for flexibility
            "dateTime" => "string",  // Keep as string for flexibility
            "time" => "string",
            "code" => "string",
            "oid" => "string",
            "id" => "string",
            "markdown" => "string",
            "unsignedInt" => "uint",
            "positiveInt" => "uint",
            "uuid" => "string",
            "xhtml" => "string",

            // Complex types - generate nested classes or use simple representations
            "HumanName" => "HumanNameDto",
            "Address" => "AddressDto",
            "ContactPoint" => "ContactPointDto",
            "Identifier" => "IdentifierDto",
            "CodeableConcept" => "CodeableConceptDto",
            "Coding" => "CodingDto",
            "Quantity" => "QuantityDto",
            "Period" => "PeriodDto",
            "Reference" => "ReferenceDto",
            "Attachment" => "AttachmentDto",
            "Range" => "RangeDto",
            "Ratio" => "RatioDto",
            "Annotation" => "AnnotationDto",
            "Signature" => "SignatureDto",
            "Meta" => "MetaDto",
            "Narrative" => "NarrativeDto",
            "Extension" => "ExtensionDto",

            // BackboneElement - will be generated as nested class
            "BackboneElement" => "object",
            "Element" => "object",

            // Resource references
            _ when fhirType.StartsWith("Reference(") => "ReferenceDto",

            // Default - use the FHIR type name as a DTO
            _ => fhirType + "Dto"
        };
    }

    private static string GetPropertyName(string path)
    {
        var parts = path.Split('.');
        var lastPart = parts.Last();

        // Handle choice types (e.g., "value[x]" -> "Value")
        if (lastPart.EndsWith("[x]"))
            lastPart = lastPart[..^3];

        return ToPascalCase(lastPart);
    }

    private static string GetJsonName(string path)
    {
        var parts = path.Split('.');
        return parts.Last().TrimEnd('[', 'x', ']');
    }

    private static string GetParentPath(string path)
    {
        var lastDot = path.LastIndexOf('.');
        return lastDot > 0 ? path[..lastDot] : path;
    }

    private static int GetDepth(string path)
    {
        return path.Count(c => c == '.');
    }

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        // Handle already PascalCase or camelCase
        var result = char.ToUpperInvariant(input[0]) + input[1..];

        // Handle kebab-case or snake_case
        var sb = new StringBuilder();
        var capitalizeNext = true;
        foreach (var c in result)
        {
            if (c == '-' || c == '_')
            {
                capitalizeNext = true;
            }
            else if (capitalizeNext)
            {
                sb.Append(char.ToUpperInvariant(c));
                capitalizeNext = false;
            }
            else
            {
                sb.Append(c);
            }
        }
        return sb.ToString();
    }

    private static bool IsValueType(string csharpType)
    {
        return csharpType is "bool" or "int" or "long" or "decimal" or "uint" or "DateTimeOffset";
    }

    private static string EscapeXml(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}

/// <summary>
/// Options for the profile code generator.
/// </summary>
public class GeneratorOptions
{
    /// <summary>
    /// Namespace for generated code. Default: "Generated.Fhir"
    /// </summary>
    public string Namespace { get; set; } = "Generated.Fhir";

    /// <summary>
    /// Override the class name (otherwise derived from profile name).
    /// </summary>
    public string? ClassNameOverride { get; set; }

    /// <summary>
    /// Only include elements marked as MustSupport. Default: false
    /// </summary>
    public bool MustSupportOnly { get; set; } = false;

    /// <summary>
    /// Only include elements that have constraints (min>0, fixed, pattern, etc.). Default: false
    /// </summary>
    public bool ConstrainedOnly { get; set; } = false;

    /// <summary>
    /// Include extension elements. Default: false
    /// </summary>
    public bool IncludeExtensions { get; set; } = false;

    /// <summary>
    /// Include metadata elements (meta, text, contained, etc.). Default: false
    /// </summary>
    public bool IncludeMetadata { get; set; } = false;
}
